# Generated by Django 5.2.17 on 2026-08-22 18:40

import kaxi.identity.models
from django.db import migrations


def activate_existing_superusers(apps, schema_editor):
    user = apps.get_model("identity", "User")
    user.objects.filter(is_superuser=True, status="invited").update(status="active", is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_userpermissionoverride_requested_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', kaxi.identity.models.KaxiUserManager()),
            ],
        ),
        migrations.RunPython(activate_existing_superusers, migrations.RunPython.noop),
    ]
