# Generated by Django 5.2.17 on 2026-08-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
