# Generated by Django 5.2.17 on 2026-08-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=32)),
            ],
            options={
                'db_table': 'md_currency',
                'constraints': [models.CheckConstraint(condition=models.Q(('decimal_places__lte', 6)), name='md_currency_decimal_places_lte_6')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name_zh', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=32)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.region')),
            ],
            options={
                'db_table': 'md_region',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('company_code', models.CharField(max_length=50, unique=True)),
                ('legal_name', models.CharField(max_length=300)),
                ('display_name', models.CharField(max_length=300)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=32)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('registered_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.region')),
            ],
            options={
                'db_table': 'sys_company',
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['parent', 'status'], name='md_region_parent_status_idx'),
        ),
    ]
