# Generated by Django 5.2.17 on 2026-08-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('uom_code', models.CharField(max_length=32, unique=True)),
                ('name_zh', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('dimension', models.CharField(choices=[('count', '数量'), ('weight', '重量'), ('length', '长度'), ('area', '面积'), ('volume', '体积'), ('other', '其他')], max_length=16)),
                ('decimal_places', models.PositiveSmallIntegerField(default=6)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=32)),
            ],
            options={
                'db_table': 'md_unit_of_measure',
                'constraints': [models.CheckConstraint(condition=models.Q(('decimal_places__lte', 6)), name='md_uom_decimal_places_lte_6')],
            },
        ),
    ]
