# Generated by Django 5.2.17 on 2026-08-22 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_unitofmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('party_no', models.CharField(max_length=50)),
                ('party_type', models.CharField(choices=[('organization', '组织'), ('person', '个人')], max_length=16)),
                ('legal_name', models.CharField(max_length=300)),
                ('display_name', models.CharField(max_length=300)),
                ('default_language', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('suspended', '暂停'), ('inactive', '停用')], default='draft', max_length=32)),
                ('risk_level', models.CharField(blank=True, max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('country_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.region')),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
            ],
            options={
                'db_table': 'mdm_party',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='master_data.party')),
                ('status', models.CharField(default='active', max_length=32)),
            ],
            options={
                'db_table': 'mdm_customer_profile',
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='master_data.party')),
                ('status', models.CharField(default='active', max_length=32)),
            ],
            options={
                'db_table': 'mdm_supplier_profile',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('address_code', models.CharField(max_length=50)),
                ('address_type', models.CharField(max_length=16)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address_line1', models.CharField(max_length=500)),
                ('address_line2', models.CharField(blank=True, max_length=500)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('country_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.region')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='master_data.party')),
            ],
            options={
                'db_table': 'mdm_address',
            },
        ),
        migrations.CreateModel(
            name='PartyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='master_data.party')),
            ],
            options={
                'db_table': 'mdm_party_contact',
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['company', 'status', 'display_name'], name='mdm_party_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('company', 'party_no'), name='mdm_party_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('party', 'address_code'), name='mdm_address_party_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='partycontact',
            index=models.Index(fields=['party', 'is_active'], name='mdm_contact_party_active_idx'),
        ),
    ]
