# Generated by Django 5.2.17 on 2026-08-22 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_sources', to='master_data.party'),
        ),
        migrations.CreateModel(
            name='PartyMergeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('match_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('match_reasons', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已合并'), ('rejected', '非重复')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('reference_counts', models.JSONField(default=dict)),
                ('canonical_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_merge_candidates', to='master_data.party')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_party_merges', to=settings.AUTH_USER_MODEL)),
                ('duplicate_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_merge_candidates', to='master_data.party')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_party_merges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mdm_party_merge_candidate',
                'indexes': [models.Index(fields=['company', 'status', '-created_at'], name='mdm_merge_queue_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'canonical_party', 'duplicate_party'), name='mdm_party_merge_pair_uniq'), models.CheckConstraint(condition=models.Q(('canonical_party', models.F('duplicate_party')), _negated=True), name='mdm_party_merge_distinct_ck'), models.CheckConstraint(condition=models.Q(('match_score__gte', 0), ('match_score__lte', 1)), name='mdm_party_merge_score_ck')],
            },
        ),
    ]
