# Generated by Django 5.2.17 on 2026-08-22 17:28

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_posted_journal_immutability'),
        ('inventory', '0004_stockcount_stockcountline_stocktransfer_and_more'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('sales', '0004_salesshipment_salesshipmentline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('case_no', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('return', '退货'), ('refund', '退款'), ('exchange', '换货'), ('reship', '补发'), ('discount', '折让'), ('claim', '索赔')], max_length=16)),
                ('reason_code', models.CharField(max_length=50)),
                ('reason_detail', models.TextField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审批'), ('approved', '已批准'), ('returning', '退货中'), ('processing', '处理中'), ('completed', '已完成'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='draft', max_length=24)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version_no', models.PositiveBigIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_aftersales_cases', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aftersales_requests', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aftersales_cases', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sal_aftersales_case',
            },
        ),
        migrations.CreateModel(
            name='AfterSalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('requested_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('received_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('accepted_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('rejected_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='aftersales.aftersalescase')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorderline')),
            ],
            options={
                'db_table': 'sal_aftersales_line',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('refund_no', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('base_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('status', models.CharField(choices=[('pending', '待退款'), ('approved', '已批准'), ('paid', '已退款'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('external_refund_id', models.CharField(blank=True, max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='aftersales.aftersalescase')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
            ],
            options={
                'db_table': 'sal_refund',
            },
        ),
        migrations.CreateModel(
            name='ReplacementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('replacement_type', models.CharField(choices=[('exchange', '换货'), ('reship', '补发')], max_length=16)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='aftersales.aftersalescase')),
                ('replacement_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder')),
            ],
            options={
                'db_table': 'sal_replacement_order',
            },
        ),
        migrations.CreateModel(
            name='ReturnReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('receipt_no', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='return_receipt', to='aftersales.aftersalescase')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sal_return_receipt',
            },
        ),
        migrations.CreateModel(
            name='ReturnReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('received_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('accepted_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('rejected_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('accepted_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_returns', to='inventory.inventorybalance')),
                ('aftersales_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='aftersales.aftersalesline')),
                ('exception_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exception_returns', to='inventory.inventorybalance')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='aftersales.returnreceipt')),
            ],
            options={
                'db_table': 'sal_return_receipt_line',
            },
        ),
        migrations.AddConstraint(
            model_name='aftersalescase',
            constraint=models.UniqueConstraint(fields=('company', 'case_no'), name='sal_after_case_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='aftersalesline',
            constraint=models.UniqueConstraint(fields=('case', 'sales_order_line'), name='sal_after_case_line_uniq'),
        ),
        migrations.AddConstraint(
            model_name='aftersalesline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_qty__gt', 0), ('received_qty__gte', 0), ('accepted_qty__gte', 0), ('rejected_qty__gte', 0)), name='sal_after_line_qty_ck'),
        ),
        migrations.AddConstraint(
            model_name='aftersalesline',
            constraint=models.CheckConstraint(condition=models.Q(('received_qty__lte', models.F('requested_qty'))), name='sal_after_received_lte_requested_ck'),
        ),
        migrations.AddConstraint(
            model_name='aftersalesline',
            constraint=models.CheckConstraint(condition=models.Q(('received_qty', django.db.models.expressions.CombinedExpression(models.F('accepted_qty'), '+', models.F('rejected_qty')))), name='sal_after_disposition_sum_ck'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('case', 'refund_no'), name='sal_refund_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('base_amount__gt', 0), ('exchange_rate__gt', 0)), name='sal_refund_amount_ck'),
        ),
        migrations.AddConstraint(
            model_name='returnreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('received_qty__gt', 0), ('accepted_qty__gte', 0), ('rejected_qty__gte', 0), ('received_qty', django.db.models.expressions.CombinedExpression(models.F('accepted_qty'), '+', models.F('rejected_qty')))), name='sal_return_receipt_qty_ck'),
        ),
    ]
