# Generated by Django 5.2.17 on 2026-08-22 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('dictionary_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'sys_dictionary_type',
            },
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('item_value', models.CharField(max_length=100)),
                ('label_zh', models.CharField(max_length=200)),
                ('label_en', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('extension_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system.dictionaryitem')),
                ('dictionary_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='system.dictionarytype')),
            ],
            options={
                'db_table': 'sys_dictionary_item',
            },
        ),
        migrations.CreateModel(
            name='NumberRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('rule_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('prefix_template', models.CharField(blank=True, max_length=100)),
                ('date_format', models.CharField(blank=True, max_length=32)),
                ('separator', models.CharField(blank=True, max_length=5)),
                ('sequence_length', models.PositiveSmallIntegerField(default=6)),
                ('reset_period', models.CharField(choices=[('never', '不重置'), ('year', '每年'), ('month', '每月'), ('day', '每日')], default='never', max_length=16)),
                ('starts_from', models.PositiveBigIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'sys_number_rule',
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=16)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='system.numberrule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sys_number_sequence',
            },
        ),
        migrations.AddConstraint(
            model_name='dictionarytype',
            constraint=models.UniqueConstraint(fields=('company', 'dictionary_code'), name='sys_dict_type_company_code_uniq', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='dictionaryitem',
            index=models.Index(fields=['dictionary_type', 'is_active', 'sort_order'], name='sys_dict_item_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='dictionaryitem',
            constraint=models.UniqueConstraint(fields=('dictionary_type', 'item_value'), name='sys_dict_item_type_value_uniq'),
        ),
        migrations.AddConstraint(
            model_name='numberrule',
            constraint=models.UniqueConstraint(fields=('company', 'rule_code'), name='sys_number_rule_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='numberrule',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_length__gte', 1), ('sequence_length__lte', 20)), name='sys_number_rule_seq_length_ck'),
        ),
        migrations.AddConstraint(
            model_name='numberrule',
            constraint=models.CheckConstraint(condition=models.Q(('starts_from__gte', 1)), name='sys_number_rule_starts_from_ck'),
        ),
        migrations.AddConstraint(
            model_name='numbersequence',
            constraint=models.UniqueConstraint(fields=('rule', 'period_key'), name='sys_number_sequence_rule_period_uniq'),
        ),
    ]
