# Generated by Django 5.2.17 on 2026-08-22 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
                ('task_version', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('source_type', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('processing', '执行中'), ('succeeded', '成功'), ('failed', '失败'), ('dead', '死信')], default='pending', max_length=16)),
                ('priority', models.SmallIntegerField(default=0)),
                ('queue', models.CharField(max_length=32)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_summary', models.TextField(blank=True)),
                ('trace_id', models.CharField(blank=True, max_length=64)),
                ('result_reference', models.CharField(blank=True, max_length=300)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'sys_background_task_execution',
                'indexes': [models.Index(fields=['status', 'queue', 'scheduled_at'], name='sys_task_status_queue_idx'), models.Index(fields=['task_name', 'finished_at'], name='sys_task_name_finish_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'task_name', 'task_version', 'idempotency_key'), name='sys_task_execution_idem_uniq', nulls_distinct=False)],
            },
        ),
    ]
