# Generated by Django 5.2.17 on 2026-08-22 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('system', '0002_backgroundtaskexecution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('batch_no', models.CharField(max_length=64)),
                ('entity_type', models.CharField(choices=[('party', '客商'), ('sku', 'SKU'), ('opening_inventory', '期初库存')], max_length=32)),
                ('source_filename', models.CharField(max_length=300)),
                ('source_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('staged', '已暂存'), ('validated', '校验通过'), ('invalid', '校验失败'), ('committed', '已提交')], default='staged', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sys_data_import_batch',
            },
        ),
        migrations.CreateModel(
            name='DataImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('source_data', models.JSONField()),
                ('normalized_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('staged', '已暂存'), ('valid', '有效'), ('invalid', '无效'), ('committed', '已提交')], default='staged', max_length=16)),
                ('errors', models.JSONField(default=list)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='system.dataimportbatch')),
            ],
            options={
                'db_table': 'sys_data_import_row',
            },
        ),
        migrations.AddConstraint(
            model_name='dataimportbatch',
            constraint=models.UniqueConstraint(fields=('company', 'batch_no'), name='sys_import_batch_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='dataimportbatch',
            constraint=models.UniqueConstraint(fields=('company', 'entity_type', 'source_sha256'), name='sys_import_source_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='dataimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='sys_import_row_uniq'),
        ),
    ]
