# Generated by Django 5.2.17 on 2026-08-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_dataimportbatch_dataimportrow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('singleton_key', models.CharField(default='global', editable=False, max_length=20, unique=True)),
                ('app_name', models.CharField(default='KAXI ERP', max_length=80)),
                ('version_name', models.CharField(default='V1.0', max_length=40)),
                ('theme', models.CharField(default='forest', max_length=20)),
                ('logo_storage_key', models.CharField(blank=True, max_length=1000)),
                ('logo_mime_type', models.CharField(blank=True, max_length=100)),
                ('background_storage_key', models.CharField(blank=True, max_length=1000)),
                ('background_mime_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'sys_branding_configuration',
            },
        ),
    ]
