# Generated by Django 5.2.17 on 2026-08-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_brandingconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('family_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('storage_key', models.CharField(max_length=1000, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('original_filename', models.CharField(max_length=500)),
                ('coverage', models.CharField(choices=[('combined', '中西文'), ('cjk_only', '仅中文'), ('latin_only', '仅西文')], max_length=20)),
                ('latin_supported', models.BooleanField(default=False)),
                ('cjk_glyph_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sys_font_asset',
            },
        ),
        migrations.AddField(
            model_name='brandingconfiguration',
            name='primary_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_for', to='system.fontasset'),
        ),
        migrations.AddField(
            model_name='brandingconfiguration',
            name='western_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='western_for', to='system.fontasset'),
        ),
    ]
