# Generated by Django 5.2.17 on 2026-08-22 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('batch_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已批准'), ('executed', '已执行')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_disposals', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_disposal_batch',
            },
        ),
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.filecategory')),
            ],
            options={
                'db_table': 'doc_file_category',
            },
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('file_no', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('security_level', models.CharField(choices=[('L1', '公开业务'), ('L2', '内部'), ('L3', '敏感'), ('L4', '高度敏感')], default='L2', max_length=2)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '有效'), ('void', '作废'), ('archived', '归档'), ('recycled', '回收站'), ('disposed', '已销毁')], default='draft', max_length=16)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('legal_hold', models.BooleanField(default=False)),
                ('legal_hold_reason', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.filecategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_file_object',
            },
        ),
        migrations.CreateModel(
            name='FileBusinessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=100)),
                ('relation_type', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_links', to='documents.fileobject')),
            ],
            options={
                'db_table': 'doc_file_business_link',
            },
        ),
        migrations.CreateModel(
            name='FileAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.fileobject')),
            ],
            options={
                'db_table': 'doc_file_audit_log',
            },
        ),
        migrations.CreateModel(
            name='DisposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('reason', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='documents.disposalbatch')),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.fileobject')),
            ],
            options={
                'db_table': 'doc_disposal_item',
            },
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('action', models.CharField(choices=[('read', '查看'), ('download', '下载'), ('manage', '管理')], max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approval_reference', models.CharField(blank=True, max_length=100)),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.fileobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_file_permission',
            },
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'doc_file_tag',
            },
        ),
        migrations.CreateModel(
            name='FileObjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.fileobject')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.filetag')),
            ],
            options={
                'db_table': 'doc_file_object_tag',
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('version_no', models.PositiveIntegerField()),
                ('original_filename', models.CharField(max_length=500)),
                ('storage_provider', models.CharField(default='minio', max_length=50)),
                ('storage_key', models.CharField(max_length=1000, unique=True)),
                ('mime_type', models.CharField(max_length=200)),
                ('extension', models.CharField(blank=True, max_length=32)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', '待扫描'), ('clean', '安全'), ('quarantined', '隔离'), ('failed', '扫描失败')], default='pending', max_length=16)),
                ('source_type', models.CharField(default='upload', max_length=32)),
                ('template_version', models.CharField(blank=True, max_length=50)),
                ('business_snapshot', models.JSONField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.fileobject')),
            ],
            options={
                'db_table': 'doc_file_version',
            },
        ),
        migrations.AddField(
            model_name='fileobject',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_files', to='documents.fileversion'),
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('retain_days', models.PositiveIntegerField()),
                ('archive_after_days', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'doc_retention_policy',
            },
        ),
        migrations.AddField(
            model_name='fileobject',
            name='retention_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.retentionpolicy'),
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('max_downloads', models.PositiveIntegerField(default=1)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('watermark', models.CharField(blank=True, max_length=300)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='documents.fileobject')),
            ],
            options={
                'db_table': 'doc_file_share_link',
            },
        ),
        migrations.AddConstraint(
            model_name='disposalbatch',
            constraint=models.UniqueConstraint(fields=('company', 'batch_no'), name='doc_disposal_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='filecategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='doc_category_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='filebusinesslink',
            constraint=models.UniqueConstraint(fields=('file_object', 'object_type', 'object_id', 'relation_type'), name='doc_file_business_link_uniq'),
        ),
        migrations.AddIndex(
            model_name='fileauditlog',
            index=models.Index(fields=['file_object', '-occurred_at'], name='doc_audit_file_idx'),
        ),
        migrations.AddConstraint(
            model_name='disposalitem',
            constraint=models.UniqueConstraint(fields=('batch', 'file_object'), name='doc_disposal_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='filepermission',
            constraint=models.UniqueConstraint(fields=('file_object', 'user', 'action'), name='doc_file_permission_uniq'),
        ),
        migrations.AddConstraint(
            model_name='filetag',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='doc_tag_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fileobjecttag',
            constraint=models.UniqueConstraint(fields=('file_object', 'tag'), name='doc_file_tag_uniq'),
        ),
        migrations.AddIndex(
            model_name='fileversion',
            index=models.Index(fields=['sha256', 'size_bytes'], name='doc_version_hash_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileversion',
            constraint=models.UniqueConstraint(fields=('file_object', 'version_no'), name='doc_file_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='retentionpolicy',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='doc_retention_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['company', 'category', 'status', 'security_level'], name='doc_file_library_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileobject',
            constraint=models.UniqueConstraint(fields=('company', 'file_no'), name='doc_file_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fileobject',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='doc_file_valid_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='sharelink',
            constraint=models.CheckConstraint(condition=models.Q(('download_count__lte', models.F('max_downloads'))), name='doc_share_download_limit_ck'),
        ),
    ]
