# Generated by Django 5.2.17 on 2026-08-22 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fin_chart_of_accounts',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('asset', '资产'), ('liability', '负债'), ('equity', '权益'), ('revenue', '收入'), ('expense', '费用')], max_length=16)),
                ('normal_balance', models.CharField(choices=[('debit', '借'), ('credit', '贷')], max_length=8)),
                ('allow_posting', models.BooleanField(default=True)),
                ('requires_party', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.chartofaccounts')),
            ],
            options={
                'db_table': 'fin_account',
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', '开放'), ('closed', '已结账'), ('reopened', '已重开')], default='open', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_fiscal_period',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('voucher_no', models.CharField(max_length=64)),
                ('entry_type', models.CharField(default='general', max_length=32)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已审核'), ('posted', '已过账'), ('reversed', '已冲销')], default='draft', max_length=16)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('total_debit_base', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_credit_base', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_journals', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='finance.fiscalperiod')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_journals', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.journalentry')),
            ],
            options={
                'db_table': 'fin_journal_entry',
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('debit_original', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('credit_original', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('debit_base', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('credit_base', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.journalentry')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'fin_journal_entry_line',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'fin_ledger',
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='finance.ledger'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='finance.ledger'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charts', to='finance.ledger'),
        ),
        migrations.CreateModel(
            name='OpenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('kind', models.CharField(choices=[('receivable', '应收'), ('payable', '应付')], max_length=16)),
                ('item_no', models.CharField(max_length=64)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('original_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('base_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('allocated_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('allocated_base_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', '未核销'), ('partial', '部分核销'), ('settled', '已核销')], default='open', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'fin_open_item',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('kind', models.CharField(choices=[('receipt', '收款'), ('payment', '付款')], max_length=16)),
                ('settlement_no', models.CharField(max_length=64)),
                ('settlement_date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('base_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('allocated_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('external_transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'fin_settlement',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('base_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.allocation')),
                ('open_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.openitem')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.settlement')),
            ],
            options={
                'db_table': 'fin_allocation',
            },
        ),
        migrations.CreateModel(
            name='ThreeWayMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('supplier_invoice_no', models.CharField(max_length=100)),
                ('invoice_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('matched_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('variance_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('status', models.CharField(default='matched', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.goodsreceipt')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.purchaseorder')),
            ],
            options={
                'db_table': 'fin_three_way_match',
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['chart', 'active', 'code'], name='fin_account_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('chart', 'code'), name='fin_account_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.UniqueConstraint(fields=('entry', 'line_no'), name='fin_journal_line_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='fin_journal_rate_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit_base', 0), ('debit_base__gt', 0)), models.Q(('credit_base__gt', 0), ('debit_base', 0)), _connector='OR'), name='fin_journal_one_side_ck'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='fin_ledger_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('company', 'ledger', 'period', 'entry_type', 'voucher_no'), name='fin_voucher_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='fin_journal_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fiscalperiod',
            constraint=models.UniqueConstraint(fields=('ledger', 'year', 'month'), name='fin_period_ym_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fiscalperiod',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='fin_period_month_ck'),
        ),
        migrations.AddConstraint(
            model_name='fiscalperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='fin_period_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccounts',
            constraint=models.UniqueConstraint(fields=('ledger', 'code', 'version'), name='fin_chart_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccounts',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='fin_chart_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='openitem',
            constraint=models.UniqueConstraint(fields=('company', 'kind', 'item_no'), name='fin_open_item_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='openitem',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0), ('base_amount__gt', 0)), name='fin_open_item_amount_ck'),
        ),
        migrations.AddConstraint(
            model_name='openitem',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gte', 0), ('allocated_amount__lte', models.F('original_amount'))), name='fin_open_item_alloc_ck'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.UniqueConstraint(fields=('company', 'kind', 'settlement_no'), name='fin_settlement_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.UniqueConstraint(condition=models.Q(('external_transaction_id', ''), _negated=True), fields=('company', 'external_transaction_id'), name='fin_settlement_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('base_amount__gt', 0)), name='fin_settlement_amount_ck'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gte', 0), ('allocated_amount__lte', models.F('amount'))), name='fin_settlement_alloc_ck'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount', 0), _negated=True), models.Q(('base_amount', 0), _negated=True)), name='fin_allocation_nonzero_ck'),
        ),
        migrations.AddConstraint(
            model_name='threewaymatch',
            constraint=models.UniqueConstraint(fields=('company', 'supplier_invoice_no'), name='fin_supplier_invoice_uniq'),
        ),
        migrations.AddConstraint(
            model_name='threewaymatch',
            constraint=models.CheckConstraint(condition=models.Q(('invoice_amount__gt', 0), ('matched_amount__gte', 0)), name='fin_match_amount_ck'),
        ),
    ]
