# Generated by Django 5.2.17 on 2026-08-22 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_posted_journal_immutability'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0003_limitededitionpool_productserial_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('cost_record_no', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('purchase', '采购'), ('material', '材料'), ('production', '生产'), ('packaging', '包装'), ('domestic_freight', '国内物流'), ('international_freight', '国际运费'), ('insurance', '保险'), ('customs', '报关'), ('platform_fee', '平台费用'), ('forwarder_fee', '货代费用'), ('aftersales', '售后'), ('labor', '人工'), ('overhead', '制造费用'), ('cogs', '销售成本')], max_length=32)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('total_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('base_total_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=100)),
                ('effective_date', models.DateField()),
                ('idempotency_key', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.costrecord')),
            ],
            options={
                'db_table': 'fin_cost_record',
                'constraints': [models.UniqueConstraint(fields=('company', 'cost_record_no'), name='fin_cost_record_no_uniq'), models.UniqueConstraint(fields=('company', 'idempotency_key'), name='fin_cost_record_idem_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('quantity', 0), _negated=True), ('unit_cost__gte', 0), models.Q(('total_cost', 0), _negated=True), ('exchange_rate__gt', 0), models.Q(('base_total_cost', 0), _negated=True)), name='fin_cost_record_values_ck')],
            },
        ),
        migrations.CreateModel(
            name='InventoryCostBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_cost_base', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('average_unit_cost_base', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'fin_inventory_cost_balance',
                'constraints': [models.UniqueConstraint(fields=('company', 'sku', 'warehouse'), name='fin_cost_balance_uniq'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0), ('total_cost_base__gte', 0), ('average_unit_cost_base__gte', 0)), name='fin_cost_balance_values_ck')],
            },
        ),
        migrations.CreateModel(
            name='SerialCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('original_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('base_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('serial', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cost', to='products.productserial')),
            ],
            options={
                'db_table': 'fin_serial_cost',
                'constraints': [models.CheckConstraint(condition=models.Q(('original_cost__gte', 0), ('exchange_rate__gt', 0), ('base_cost__gte', 0)), name='fin_serial_cost_values_ck')],
            },
        ),
    ]
