# Generated by Django 5.2.17 on 2026-08-22 18:03

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cost_record_immutability'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('asset_no', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('acquisition_date', models.DateField()),
                ('in_service_date', models.DateField()),
                ('original_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('residual_value', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('useful_life_months', models.PositiveIntegerField()),
                ('accumulated_depreciation', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '使用中'), ('fully_depreciated', '已提足'), ('disposed', '已处置')], default='draft', max_length=24)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_proceeds', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_fixed_asset',
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.fiscalperiod')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciations', to='finance.fixedasset')),
            ],
            options={
                'db_table': 'fin_depreciation_entry',
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('run_no', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('calculated', '已计算'), ('approved', '已批准'), ('posted', '已计提'), ('paid', '已发放')], default='draft', max_length=16)),
                ('gross_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('deduction_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('calculated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculated_payrolls', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.fiscalperiod')),
            ],
            options={
                'db_table': 'fin_payroll_run',
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('gross_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('deduction_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('detail', models.JSONField(default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.payrollrun')),
            ],
            options={
                'db_table': 'fin_payroll_line',
            },
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('direction', models.CharField(choices=[('input', '进项'), ('output', '销项')], max_length=8)),
                ('invoice_code', models.CharField(blank=True, max_length=64)),
                ('invoice_no', models.CharField(max_length=64)),
                ('issue_date', models.DateField()),
                ('amount_excluding_tax', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tax_detail', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('verified', '已核验'), ('posted', '已入账'), ('void', '已作废')], default='draft', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_tax_invoice',
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('claim_no', models.CharField(max_length=64)),
                ('expense_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('base_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准'), ('posted', '已入账'), ('paid', '已支付'), ('rejected', '已拒绝')], default='draft', max_length=16)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expense_claims', to=settings.AUTH_USER_MODEL)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
            ],
            options={
                'db_table': 'fin_expense_claim',
                'constraints': [models.UniqueConstraint(fields=('company', 'claim_no'), name='fin_claim_no_uniq'), models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('base_amount__gt', 0), ('exchange_rate__gt', 0)), name='fin_claim_amount_ck')],
            },
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.UniqueConstraint(fields=('company', 'asset_no'), name='fin_asset_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.CheckConstraint(condition=models.Q(('original_cost__gt', 0), ('residual_value__gte', 0), ('residual_value__lt', models.F('original_cost')), ('accumulated_depreciation__gte', 0)), name='fin_asset_values_ck'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.UniqueConstraint(fields=('asset', 'period'), name='fin_asset_period_dep_uniq'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fin_dep_amount_ck'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('company', 'run_no'), name='fin_payroll_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0), ('deduction_amount__gte', 0), ('net_amount__gte', 0)), name='fin_payroll_totals_ck'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('payroll', 'employee'), name='fin_payroll_employee_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0), ('deduction_amount__gte', 0), ('net_amount', django.db.models.expressions.CombinedExpression(models.F('gross_amount'), '-', models.F('deduction_amount')))), name='fin_payroll_line_values_ck'),
        ),
        migrations.AddConstraint(
            model_name='taxinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'direction', 'invoice_code', 'invoice_no'), name='fin_tax_invoice_uniq'),
        ),
        migrations.AddConstraint(
            model_name='taxinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_excluding_tax__gte', 0), ('tax_amount__gte', 0), ('total_amount', django.db.models.expressions.CombinedExpression(models.F('amount_excluding_tax'), '+', models.F('tax_amount')))), name='fin_tax_invoice_amount_ck'),
        ),
    ]
