# Generated by Django 5.2.17 on 2026-08-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_fixedasset_depreciationentry_payrollrun_payrollline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cash_flow_category',
            field=models.CharField(blank=True, choices=[('', '不适用'), ('operating', '经营活动'), ('investing', '投资活动'), ('financing', '筹资活动'), ('cash', '现金及现金等价物')], default='', max_length=16),
        ),
    ]
