# Generated by Django 5.2.17 on 2026-08-22 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0003_limitededitionpool_productserial_and_more'),
        ('sales', '0004_salesshipment_salesshipmentline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('shipment_no', models.CharField(max_length=100)),
                ('trade_type', models.CharField(max_length=32)),
                ('transport_mode', models.CharField(max_length=32)),
                ('carrier_name', models.CharField(blank=True, max_length=300)),
                ('tracking_or_booking_no', models.CharField(blank=True, max_length=200)),
                ('planned_ship_at', models.DateTimeField(blank=True, null=True)),
                ('actual_ship_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=500)),
                ('destination', models.CharField(blank=True, max_length=500)),
                ('package_count', models.PositiveIntegerField(default=0)),
                ('gross_weight', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('net_weight', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('planned', '计划中'), ('arranging', '待安排运输'), ('confirmed', '已确认运输'), ('packing', '待装箱'), ('documents', '待单证'), ('dispatch_ready', '待交运'), ('dispatched', '已交运'), ('in_transit', '在途'), ('arrived', '已到达'), ('delivered', '已签收'), ('completed', '已完成'), ('exception', '异常')], default='planned', max_length=24)),
                ('exception_type', models.CharField(blank=True, max_length=50)),
                ('exception_detail', models.TextField(blank=True)),
                ('version_no', models.PositiveBigIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('forwarder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'trd_shipment',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('package_no', models.CharField(max_length=100)),
                ('package_type', models.CharField(blank=True, max_length=50)),
                ('length', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('width', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('height', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('net_weight', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('gross_weight', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('shipping_mark', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', '草稿箱'), ('packing', '装箱中'), ('review', '待复核'), ('sealed', '已封箱'), ('dispatched', '已交运')], default='draft', max_length=16)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='trade.shipment')),
            ],
            options={
                'db_table': 'trd_package',
            },
        ),
        migrations.CreateModel(
            name='ShipmentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('claim_no', models.CharField(max_length=100)),
                ('claim_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('status', models.CharField(default='open', max_length=16)),
                ('description', models.TextField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='trade.shipment')),
            ],
            options={
                'db_table': 'trd_shipment_claim',
            },
        ),
        migrations.CreateModel(
            name='ShipmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('milestone_type', models.CharField(max_length=50)),
                ('occurred_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=500)),
                ('detail', models.JSONField(default=dict)),
                ('external_event_id', models.CharField(blank=True, max_length=200)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='trade.shipment')),
            ],
            options={
                'db_table': 'trd_shipment_milestone',
            },
        ),
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trade.shipment')),
            ],
            options={
                'db_table': 'trd_shipment_order',
            },
        ),
        migrations.CreateModel(
            name='TradeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('contract_no', models.CharField(max_length=100)),
                ('trade_type', models.CharField(max_length=32)),
                ('contract_date', models.DateField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('incoterm', models.CharField(blank=True, max_length=10)),
                ('incoterm_place', models.CharField(blank=True, max_length=300)),
                ('payment_terms', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已批准'), ('active', '履行中'), ('completed', '已完成'), ('terminated', '已终止')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_trade_contracts', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trade_contracts', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'trd_contract',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderTradeDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='trade_detail', serialize=False, to='sales.salesorder')),
                ('incoterm', models.CharField(blank=True, max_length=10)),
                ('incoterm_place', models.CharField(blank=True, max_length=300)),
                ('origin_place', models.CharField(blank=True, max_length=300)),
                ('origin_port', models.CharField(blank=True, max_length=300)),
                ('destination_port', models.CharField(blank=True, max_length=300)),
                ('final_destination', models.CharField(blank=True, max_length=500)),
                ('transport_mode', models.CharField(max_length=32)),
                ('planned_ship_date', models.DateField(blank=True, null=True)),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('deposit_rate', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('declaration_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('freight_forwarder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trade.tradecontract')),
            ],
            options={
                'db_table': 'trd_sales_order_detail',
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='trade.package')),
                ('product_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productserial')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorderline')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
            ],
            options={
                'db_table': 'trd_package_item',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='trd_package_qty_ck'), models.UniqueConstraint(condition=models.Q(('product_serial__isnull', False)), fields=('product_serial',), name='trd_package_serial_uniq'), models.CheckConstraint(condition=models.Q(('product_serial__isnull', True), ('quantity', 1), _connector='OR'), name='trd_package_serial_qty_ck')],
            },
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('company', 'shipment_no'), name='trd_shipment_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight__gte', 0), ('net_weight__gte', 0), ('volume__gte', 0)), name='trd_shipment_measures_ck'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('shipment', 'package_no'), name='trd_package_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('length__gte', 0), ('width__gte', 0), ('height__gte', 0), ('net_weight__gte', 0), ('gross_weight__gte', 0), ('volume__gte', 0)), name='trd_package_measures_ck'),
        ),
        migrations.AddConstraint(
            model_name='shipmentclaim',
            constraint=models.UniqueConstraint(fields=('shipment', 'claim_no'), name='trd_shipment_claim_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='shipmentclaim',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='trd_claim_amount_ck'),
        ),
        migrations.AddConstraint(
            model_name='shipmentmilestone',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id', ''), _negated=True), fields=('shipment', 'external_event_id'), name='trd_milestone_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='shipmentorder',
            constraint=models.UniqueConstraint(fields=('shipment', 'sales_order'), name='trd_shipment_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tradecontract',
            constraint=models.UniqueConstraint(fields=('company', 'contract_no'), name='trd_contract_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tradecontract',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='trd_contract_amount_ck'),
        ),
        migrations.AddConstraint(
            model_name='tradecontract',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='trd_contract_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='salesordertradedetail',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_rate__gte', 0), ('deposit_rate__lte', 1)), name='trd_order_deposit_rate_ck'),
        ),
    ]
