# Generated by Django 5.2.17 on 2026-08-22 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('trade', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('declaration_no', models.CharField(blank=True, max_length=100)),
                ('customs_office', models.CharField(max_length=200)),
                ('declaration_mode', models.CharField(max_length=50)),
                ('declaration_date', models.DateField(blank=True, null=True)),
                ('declared_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('item_snapshot', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已申报'), ('cleared', '已放行'), ('rejected', '退单'), ('cancelled', '取消')], default='draft', max_length=16)),
                ('rebate_status', models.CharField(default='not_started', max_length=32)),
                ('rebate_reference', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('declaration_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customs_declaration', to='trade.shipment')),
            ],
            options={
                'db_table': 'trd_customs_declaration',
                'constraints': [models.CheckConstraint(condition=models.Q(('declared_amount__gte', 0)), name='trd_customs_amount_ck'), models.UniqueConstraint(condition=models.Q(('declaration_no', ''), _negated=True), fields=('company', 'declaration_no'), name='trd_customs_company_no_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ForwarderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('settlement_no', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('receivable_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('fee_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('received_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('difference_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('detail_snapshot', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('paid', '已支付'), ('reconciled', '已对账')], default='draft', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'trd_forwarder_settlement',
                'constraints': [models.UniqueConstraint(fields=('company', 'settlement_no'), name='trd_forwarder_settlement_no_uniq'), models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='trd_forwarder_settlement_period_ck'), models.CheckConstraint(condition=models.Q(('receivable_amount__gte', 0), ('fee_amount__gte', 0), ('received_amount__gte', 0)), name='trd_forwarder_settlement_amounts_ck')],
            },
        ),
        migrations.CreateModel(
            name='OverseasWarehouseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('external_warehouse_code', models.CharField(blank=True, max_length=100)),
                ('customs_mode', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('country_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.region')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='overseas_profile', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'trd_overseas_warehouse',
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_warehouse_code', ''), _negated=True), fields=('company', 'external_warehouse_code'), name='trd_overseas_wh_external_uniq')],
            },
        ),
        migrations.CreateModel(
            name='TradeCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('cost_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('base_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('allocation_basis', models.CharField(max_length=32)),
                ('allocation_snapshot', models.JSONField(default=list)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('estimated', '预估'), ('confirmed', '已确认'), ('settled', '已结算'), ('reversed', '已冲销')], default='estimated', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('service_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_costs', to='trade.shipment')),
            ],
            options={
                'db_table': 'trd_cost',
                'indexes': [models.Index(fields=['shipment', 'cost_type', 'status'], name='trd_cost_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('exchange_rate__gt', 0), ('base_amount__gte', 0)), name='trd_cost_amounts_ck')],
            },
        ),
        migrations.CreateModel(
            name='TradeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('document_type', models.CharField(max_length=32)),
                ('document_no', models.CharField(max_length=100)),
                ('language', models.CharField(default='zh-CN', max_length=16)),
                ('template_version', models.CharField(max_length=50)),
                ('snapshot', models.JSONField(default=dict)),
                ('content_sha256', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('generated', '已生成'), ('issued', '已签发'), ('void', '已作废')], default='draft', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trade_documents', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_trade_documents', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='trade.shipment')),
            ],
            options={
                'db_table': 'trd_document',
                'indexes': [models.Index(fields=['shipment', 'document_type', 'status'], name='trd_doc_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'document_no'), name='trd_document_company_no_uniq')],
            },
        ),
    ]
