# Generated by Django 5.2.17 on 2026-08-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_unitofmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('warehouse_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'wms_warehouse',
            },
        ),
        migrations.CreateModel(
            name='WarehouseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('area_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('area_type', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'wms_area',
            },
        ),
        migrations.CreateModel(
            name='WarehouseRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('rack_code', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='warehouse.warehousearea')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'wms_rack',
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('location_code', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('location_type', models.CharField(choices=[('storage', '存储'), ('staging', '暂存'), ('inspection', '质检'), ('exception', '异常'), ('picking', '拣货')], max_length=32)),
                ('allow_mixed_sku', models.BooleanField(default=False)),
                ('capacity_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('capacity_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('capacity_volume', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('active', '启用'), ('blocked', '冻结'), ('inactive', '停用')], default='active', max_length=32)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='warehouse.warehousearea')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='warehouse.warehouse')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='warehouse.warehouserack')),
            ],
            options={
                'db_table': 'wms_location',
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'warehouse_code'), name='wms_warehouse_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='warehousearea',
            constraint=models.UniqueConstraint(fields=('warehouse', 'area_code'), name='wms_area_warehouse_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='warehouserack',
            constraint=models.UniqueConstraint(fields=('warehouse', 'rack_code'), name='wms_rack_warehouse_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['warehouse', 'area', 'status'], name='wms_location_area_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'location_code'), name='wms_location_warehouse_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_qty__isnull', True), ('capacity_qty__gte', 0), _connector='OR'), name='wms_location_capacity_qty_ck'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_weight__isnull', True), ('capacity_weight__gte', 0), _connector='OR'), name='wms_location_capacity_weight_ck'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_volume__isnull', True), ('capacity_volume__gte', 0), _connector='OR'), name='wms_location_capacity_volume_ck'),
        ),
    ]
