# Generated by Django 5.2.17 on 2026-08-22 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockcount_stockcountline_stocktransfer_and_more'),
        ('master_data', '0004_party_merged_at_party_merged_by_party_merged_into_and_more'),
        ('products', '0003_limitededitionpool_productserial_and_more'),
        ('purchasing', '0002_purchaserequisition_purchaserequisitionline_and_more'),
        ('sales', '0006_presalecampaign_presaleallocation_supplydemand_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('task_no', models.CharField(max_length=100)),
                ('task_type', models.CharField(choices=[('putaway', '上架'), ('pick', '拣货'), ('pack', '打包复核')], max_length=16)),
                ('wave_no', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('released', '已下达'), ('in_progress', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=16)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_warehouse_tasks', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchasing.goodsreceipt')),
                ('sales_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesshipment')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'wms_task',
            },
        ),
        migrations.CreateModel(
            name='WarehouseTaskLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('planned_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('scanned_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('completed_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('exception_code', models.CharField(blank=True, max_length=50)),
                ('exception_detail', models.TextField(blank=True)),
                ('sales_shipment_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesshipmentline')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('source_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybalance')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouselocation')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='warehouse.warehousetask')),
            ],
            options={
                'db_table': 'wms_task_line',
            },
        ),
        migrations.CreateModel(
            name='WarehouseScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(max_length=32)),
                ('scanned_value', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='warehouse.warehousetask')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='warehouse.warehousetaskline')),
            ],
            options={
                'db_table': 'wms_scan_event',
            },
        ),
        migrations.AddIndex(
            model_name='warehousetask',
            index=models.Index(fields=['company', 'warehouse', 'status', 'task_type'], name='wms_task_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehousetask',
            constraint=models.UniqueConstraint(fields=('company', 'task_no'), name='wms_task_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='warehousetask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('goods_receipt__isnull', False), ('sales_shipment__isnull', True), ('task_type', 'putaway')), models.Q(('goods_receipt__isnull', True), ('sales_shipment__isnull', False), ('task_type__in', ['pick', 'pack'])), _connector='OR'), name='wms_task_source_ck'),
        ),
        migrations.AddConstraint(
            model_name='warehousetaskline',
            constraint=models.UniqueConstraint(fields=('task', 'line_no'), name='wms_task_line_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='warehousetaskline',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gt', 0), ('scanned_qty__gte', 0), ('completed_qty__gte', 0), ('planned_qty__gte', models.F('scanned_qty')), ('scanned_qty__gte', models.F('completed_qty'))), name='wms_task_line_qty_ck'),
        ),
        migrations.AddIndex(
            model_name='warehousescanevent',
            index=models.Index(fields=['task', 'occurred_at', 'id'], name='wms_scan_task_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehousescanevent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='wms_scan_qty_ck'),
        ),
    ]
