# Generated by Django 5.2.17 on 2026-08-22 14:04

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_unitofmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('brand_code', models.CharField(max_length=100)),
                ('name_zh', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'prd_brand',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('category_code', models.CharField(max_length=100)),
                ('name_zh', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productcategory')),
            ],
            options={
                'db_table': 'prd_category',
            },
        ),
        migrations.CreateModel(
            name='ProductSpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('spu_code', models.CharField(max_length=100)),
                ('name_zh', models.CharField(max_length=500)),
                ('name_en', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('inactive', '停用')], default='draft', max_length=32)),
                ('extension_data', models.JSONField(blank=True, default=dict)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'prd_spu',
            },
        ),
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('sku_code', models.CharField(max_length=100)),
                ('name_zh', models.CharField(max_length=500)),
                ('name_en', models.CharField(blank=True, max_length=500)),
                ('is_serialized', models.BooleanField(default=False)),
                ('is_limited_edition', models.BooleanField(default=False)),
                ('is_lot_tracked', models.BooleanField(default=False)),
                ('allow_oversell', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('inactive', '停用'), ('discontinued', '终止')], default='draft', max_length=32)),
                ('base_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasure')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='products.productspu')),
            ],
            options={
                'db_table': 'prd_sku',
            },
        ),
        migrations.CreateModel(
            name='SkuBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('barcode_type', models.CharField(choices=[('ean13', 'EAN-13'), ('upc', 'UPC'), ('code128', 'Code 128'), ('qr', '二维码'), ('internal', '内部码')], max_length=16)),
                ('barcode_value', models.CharField(max_length=200)),
                ('normalized_value', models.CharField(max_length=200)),
                ('purpose', models.CharField(blank=True, max_length=50)),
                ('channel_code', models.CharField(blank=True, max_length=50)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcodes', to='products.productsku')),
            ],
            options={
                'db_table': 'prd_sku_barcode',
            },
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('company', 'brand_code'), name='prd_brand_company_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['company', 'parent', 'is_active'], name='prd_category_tree_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('company', 'category_code'), name='prd_category_company_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='productspu',
            index=models.Index(fields=['company', 'category', 'status'], name='prd_spu_catalog_idx'),
        ),
        migrations.AddConstraint(
            model_name='productspu',
            constraint=models.UniqueConstraint(fields=('company', 'spu_code'), name='prd_spu_company_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['company', 'spu', 'status'], name='prd_sku_spu_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(django.db.models.functions.text.Lower('name_zh'), name='prd_sku_name_zh_lower_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsku',
            constraint=models.UniqueConstraint(fields=('company', 'sku_code'), name='prd_sku_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productsku',
            constraint=models.CheckConstraint(condition=models.Q(('is_limited_edition', False), ('is_serialized', True), _connector='OR'), name='prd_sku_limited_requires_serial_ck'),
        ),
        migrations.AddIndex(
            model_name='skubarcode',
            index=models.Index(fields=['sku', 'is_active'], name='prd_barcode_sku_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='skubarcode',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_value'), name='prd_barcode_company_value_uniq'),
        ),
        migrations.AddConstraint(
            model_name='skubarcode',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='prd_barcode_valid_period_ck'),
        ),
    ]
