# Generated by Django 5.2.17 on 2026-08-22 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('material_code', models.CharField(max_length=100)),
                ('name_zh', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('is_high_value', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'prd_material',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('attribute_code', models.CharField(max_length=100)),
                ('name_zh', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('data_type', models.CharField(choices=[('text', '文本'), ('number', '数值'), ('boolean', '布尔'), ('choice', '选项')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'prd_attribute',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_rules', to='products.productcategory')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productattribute')),
            ],
            options={
                'db_table': 'prd_category_attribute',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('value_code', models.CharField(max_length=100)),
                ('label_zh', models.CharField(max_length=200)),
                ('label_en', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='products.productattribute')),
            ],
            options={
                'db_table': 'prd_attribute_value',
            },
        ),
        migrations.CreateModel(
            name='ProductTradeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('language', models.CharField(max_length=20)),
                ('declared_name', models.CharField(max_length=500)),
                ('hs_code', models.CharField(blank=True, max_length=50)),
                ('declaration_elements', models.JSONField(blank=True, default=dict)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('country_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade_profiles', to='master_data.region')),
                ('declaration_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasure')),
                ('origin_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_products', to='master_data.region')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_profiles', to='products.productsku')),
            ],
            options={
                'db_table': 'prd_trade_profile',
            },
        ),
        migrations.CreateModel(
            name='SkuAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('text_value', models.CharField(blank=True, max_length=500)),
                ('number_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productattribute')),
                ('choice_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.attributevalue')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_values', to='products.productsku')),
            ],
            options={
                'db_table': 'prd_sku_attribute_value',
            },
        ),
        migrations.CreateModel(
            name='SkuMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('content_percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('standard_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.material')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='products.productsku')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasure')),
            ],
            options={
                'db_table': 'prd_sku_material',
            },
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('company', 'material_code'), name='prd_material_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('company', 'attribute_code'), name='prd_attribute_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='categoryattribute',
            constraint=models.UniqueConstraint(fields=('category', 'attribute'), name='prd_category_attribute_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'value_code'), name='prd_attribute_value_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='producttradeprofile',
            constraint=models.UniqueConstraint(fields=('sku', 'country_region', 'language', 'valid_from'), name='prd_trade_profile_scope_start_uniq', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='producttradeprofile',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='prd_trade_profile_period_ck'),
        ),
        migrations.AddConstraint(
            model_name='producttradeprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('net_weight__isnull', True), ('net_weight__gte', 0), _connector='OR'), models.Q(('gross_weight__isnull', True), ('gross_weight__gte', 0), _connector='OR'), models.Q(('volume__isnull', True), ('volume__gte', 0), _connector='OR')), name='prd_trade_profile_measure_ck'),
        ),
        migrations.AddConstraint(
            model_name='skuattributevalue',
            constraint=models.UniqueConstraint(fields=('sku', 'attribute'), name='prd_sku_attribute_uniq'),
        ),
        migrations.AddConstraint(
            model_name='skumaterial',
            constraint=models.UniqueConstraint(fields=('sku', 'material'), name='prd_sku_material_uniq'),
        ),
        migrations.AddConstraint(
            model_name='skumaterial',
            constraint=models.CheckConstraint(condition=models.Q(('content_percentage__isnull', True), models.Q(('content_percentage__gte', 0), ('content_percentage__lte', 100)), _connector='OR'), name='prd_sku_material_percentage_ck'),
        ),
        migrations.AddConstraint(
            model_name='skumaterial',
            constraint=models.CheckConstraint(condition=models.Q(('standard_quantity__isnull', True), ('standard_quantity__gte', 0), _connector='OR'), name='prd_sku_material_quantity_ck'),
        ),
    ]
