# Generated by Django 5.2.17 on 2026-08-22 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0002_material_productattribute_categoryattribute_and_more'),
        ('sales', '0004_salesshipment_salesshipmentline_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedEditionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('edition_code', models.CharField(max_length=100)),
                ('total_limit', models.PositiveBigIntegerField()),
                ('numbering_rule', models.JSONField(default=dict)),
                ('allocated_count', models.PositiveBigIntegerField(default=0)),
                ('produced_good_count', models.PositiveBigIntegerField(default=0)),
                ('next_sort_value', models.PositiveBigIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('closed', '关闭')], default='draft', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limited_pools', to='products.productsku')),
            ],
            options={
                'db_table': 'prd_limited_edition_pool',
            },
        ),
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('serial_no', models.CharField(max_length=100)),
                ('serial_sort_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', '已规划'), ('waiting_production', '待生产'), ('in_production', '生产中'), ('in_stock', '在库可售'), ('reserved', '已预留'), ('picked', '已拣货'), ('shipped', '已发货'), ('sold', '已售完成'), ('ng', 'NG'), ('waiting_rework', '待返工'), ('waiting_reproduction', '待重生产'), ('scrapped', '报废'), ('void', '作废')], default='planned', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('current_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
                ('current_production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productionorder')),
                ('current_sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder')),
                ('limited_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='products.limitededitionpool')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouselocation')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='products.productsku')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'prd_product_serial',
            },
        ),
        migrations.CreateModel(
            name='SerialProductionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('attempt_no', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('in_progress', '生产中'), ('good', '合格'), ('ng', 'NG'), ('cancelled', '取消')], default='in_progress', max_length=32)),
                ('ng_reason', models.TextField(blank=True)),
                ('inspection_reference', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('previous_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.serialproductionattempt')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_attempts', to='manufacturing.productionorder')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_attempts', to='products.productserial')),
            ],
            options={
                'db_table': 'prd_serial_production_attempt',
            },
        ),
        migrations.CreateModel(
            name='SerialReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('allocation_type', models.CharField(choices=[('automatic', '自动分配'), ('specified', '指定编号')], max_length=32)),
                ('status', models.CharField(choices=[('active', '有效'), ('released', '已释放'), ('consumed', '已消耗'), ('expired', '已过期')], default='active', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('released_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_reservations', to='sales.salesorderline')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.productserial')),
            ],
            options={
                'db_table': 'prd_serial_reservation',
            },
        ),
        migrations.CreateModel(
            name='SerialShipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('status', models.CharField(choices=[('assigned', '已分配'), ('picked', '已拣货'), ('shipped', '已发货')], default='assigned', max_length=32)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_assignment', to='products.serialreservation')),
                ('serial', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_assignment', to='products.productserial')),
                ('shipment_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_assignments', to='sales.salesshipmentline')),
            ],
            options={
                'db_table': 'prd_serial_shipment_assignment',
            },
        ),
        migrations.CreateModel(
            name='SerialStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('reference_type', models.CharField(blank=True, max_length=80)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='products.productserial')),
            ],
            options={
                'db_table': 'prd_serial_status_history',
            },
        ),
        migrations.AddConstraint(
            model_name='limitededitionpool',
            constraint=models.UniqueConstraint(fields=('company', 'edition_code'), name='prd_limited_pool_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='limitededitionpool',
            constraint=models.UniqueConstraint(fields=('sku', 'edition_code'), name='prd_limited_pool_sku_edition_uniq'),
        ),
        migrations.AddConstraint(
            model_name='limitededitionpool',
            constraint=models.CheckConstraint(condition=models.Q(('total_limit__gt', 0)), name='prd_limited_pool_total_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='limitededitionpool',
            constraint=models.CheckConstraint(condition=models.Q(('total_limit__gte', models.F('allocated_count'))), name='prd_limited_pool_allocated_lte_total_ck'),
        ),
        migrations.AddConstraint(
            model_name='limitededitionpool',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_count__gte', models.F('produced_good_count'))), name='prd_limited_pool_good_lte_allocated_ck'),
        ),
        migrations.AddIndex(
            model_name='productserial',
            index=models.Index(fields=['company', 'sku', 'status'], name='prd_serial_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='productserial',
            constraint=models.UniqueConstraint(fields=('company', 'sku', 'serial_no'), name='prd_serial_company_sku_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productserial',
            constraint=models.UniqueConstraint(condition=models.Q(('limited_pool__isnull', False)), fields=('limited_pool', 'serial_sort_value'), name='prd_serial_pool_sort_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serialproductionattempt',
            constraint=models.UniqueConstraint(fields=('serial', 'attempt_no'), name='prd_serial_attempt_no_uniq'),
        ),
        migrations.AddIndex(
            model_name='serialreservation',
            index=models.Index(fields=['sales_order_line', 'status'], name='prd_serial_res_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='serialreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('serial',), name='prd_serial_one_active_reservation_uniq'),
        ),
        migrations.AddIndex(
            model_name='serialstatushistory',
            index=models.Index(fields=['serial', 'occurred_at'], name='prd_serial_history_idx'),
        ),
    ]
