# Generated by Django 5.2.17 on 2026-08-22 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('definition_code', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('retired', '停用')], default='draft', max_length=16)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'wf_approval_definition',
            },
        ),
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('step_no', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('approval_mode', models.CharField(choices=[('any', '任一通过'), ('all', '全部通过')], default='any', max_length=8)),
                ('timeout_hours', models.PositiveIntegerField(default=24)),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.role')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='workflow.approvaldefinition')),
            ],
            options={
                'db_table': 'wf_approval_node',
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('rule_code', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=80)),
                ('trigger_type', models.CharField(max_length=80)),
                ('condition_data', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=100)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.approvaldefinition')),
            ],
            options={
                'db_table': 'wf_approval_rule',
            },
        ),
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('business_type', models.CharField(max_length=80)),
                ('business_id', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('business_snapshot', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.approvaldefinition')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.approvalrule')),
            ],
            options={
                'db_table': 'wf_approval_instance',
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已拒绝'), ('transferred', '已转交'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to=settings.AUTH_USER_MODEL)),
                ('assignee_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.role')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflow.approvalinstance')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.approvalnode')),
                ('transferred_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.approvaltask')),
            ],
            options={
                'db_table': 'wf_approval_task',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('business_type', models.CharField(blank=True, max_length=80)),
                ('business_id', models.CharField(blank=True, max_length=100)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sys_notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('notification_type', models.CharField(max_length=50)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sys_notification_preference',
            },
        ),
        migrations.AddConstraint(
            model_name='approvaldefinition',
            constraint=models.UniqueConstraint(fields=('company', 'definition_code', 'version'), name='wf_definition_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='approvaldefinition',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='wf_definition_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='approvalnode',
            constraint=models.UniqueConstraint(fields=('definition', 'step_no'), name='wf_node_step_uniq'),
        ),
        migrations.AddConstraint(
            model_name='approvalnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approver_role__isnull', True), ('approver_user__isnull', False)), models.Q(('approver_role__isnull', False), ('approver_user__isnull', True)), _connector='OR'), name='wf_node_one_approver_ck'),
        ),
        migrations.AddConstraint(
            model_name='approvalrule',
            constraint=models.UniqueConstraint(fields=('company', 'rule_code'), name='wf_rule_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='approvalinstance',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='wf_instance_idem_uniq'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['assignee', 'status', 'due_at'], name='wf_task_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvaltask',
            constraint=models.CheckConstraint(condition=models.Q(('assignee__isnull', False), ('assignee_role__isnull', False), _connector='OR'), name='wf_task_assignee_ck'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at', '-created_at'], name='sys_notice_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'notification_type'), name='sys_notice_pref_uniq'),
        ),
    ]
