# Generated by Django 5.2.17 on 2026-08-22 14:14

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0002_material_productattribute_categoryattribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('channel_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'sal_channel',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('order_no', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('allocating', '分配中'), ('allocated', '已分配'), ('fulfilling', '履约中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=32)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.saleschannel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.address')),
            ],
            options={
                'db_table': 'sal_order',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField()),
                ('ordered_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('reserved_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('shipped_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('cancelled_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.salesorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
            ],
            options={
                'db_table': 'sal_order_line',
            },
        ),
        migrations.AddConstraint(
            model_name='saleschannel',
            constraint=models.UniqueConstraint(fields=('company', 'channel_code'), name='sal_channel_company_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', 'status', 'order_date'], name='sal_order_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('company', 'order_no'), name='sal_order_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('order', 'line_no'), name='sal_order_line_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gt', 0)), name='sal_order_line_ordered_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__gte', 0), ('shipped_qty__gte', 0), ('cancelled_qty__gte', 0)), name='sal_order_line_quantities_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gte', django.db.models.expressions.CombinedExpression(models.F('shipped_qty'), '+', models.F('cancelled_qty')))), name='sal_order_line_shipped_cancelled_lte_ordered_ck'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('reserved_qty'), '+', models.F('shipped_qty')), '+', models.F('cancelled_qty')))), name='sal_order_line_committed_lte_ordered_ck'),
        ),
    ]
