# Generated by Django 5.2.17 on 2026-08-22 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0002_material_productattribute_categoryattribute_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('confirmed_version', models.PositiveIntegerField()),
                ('result_status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'sal_order_confirmation',
            },
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='price_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='price_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__isnull', True), ('unit_price__gte', 0), _connector='OR'), name='sal_order_line_unit_price_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__isnull', True), ('line_total__gte', 0), _connector='OR'), name='sal_order_line_total_nonnegative_ck'),
        ),
        migrations.AddField(
            model_name='salesorderconfirmation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='salesorderconfirmation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='sales.salesorder'),
        ),
        migrations.AddConstraint(
            model_name='salesorderconfirmation',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='sal_confirmation_company_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='salesorderconfirmation',
            constraint=models.UniqueConstraint(fields=('order', 'confirmed_version'), name='sal_confirmation_order_version_uniq'),
        ),
    ]
