# Generated by Django 5.2.17 on 2026-08-22 14:23

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('sales', '0002_salesorderconfirmation_salesorderline_line_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('permanent_limit', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('temporary_limit', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('temporary_valid_to', models.DateTimeField(blank=True, null=True)),
                ('committed_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('receivable_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('active', '启用'), ('frozen', '冻结'), ('closed', '关闭')], default='active', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'sal_credit_account',
            },
        ),
        migrations.CreateModel(
            name='CreditCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('released_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('converted_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('approval_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '占用中'), ('released', '已释放'), ('converted', '已转应收')], default='active', max_length=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='sales.creditaccount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_commitments', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sal_credit_commitment',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sal_order_status_history',
            },
        ),
        migrations.AddConstraint(
            model_name='creditaccount',
            constraint=models.UniqueConstraint(fields=('company', 'customer', 'currency'), name='sal_credit_account_scope_uniq'),
        ),
        migrations.AddConstraint(
            model_name='creditaccount',
            constraint=models.CheckConstraint(condition=models.Q(('permanent_limit__gte', 0), ('temporary_limit__gte', 0), ('committed_amount__gte', 0), ('receivable_amount__gte', 0)), name='sal_credit_account_amounts_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='creditcommitment',
            constraint=models.UniqueConstraint(fields=('account', 'order'), name='sal_credit_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='creditcommitment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sal_credit_commitment_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='creditcommitment',
            constraint=models.CheckConstraint(condition=models.Q(('released_amount__gte', 0), ('converted_amount__gte', 0), ('amount__gte', django.db.models.expressions.CombinedExpression(models.F('released_amount'), '+', models.F('converted_amount')))), name='sal_credit_commitment_usage_ck'),
        ),
        migrations.AddIndex(
            model_name='salesorderstatushistory',
            index=models.Index(fields=['order', 'occurred_at'], name='sal_order_history_time_idx'),
        ),
    ]
