# Generated by Django 5.2.17 on 2026-08-22 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockcount_stockcountline_stocktransfer_and_more'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('sales', '0003_creditaccount_creditcommitment_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('shipment_no', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('picking', '拣货中'), ('picked', '已拣货'), ('verified', '已复核'), ('shipped', '已发货'), ('delivered', '已签收'), ('cancelled', '已取消')], default='draft', max_length=32)),
                ('version_no', models.PositiveBigIntegerField(default=1)),
                ('carrier_code', models.CharField(blank=True, max_length=100)),
                ('tracking_no', models.CharField(blank=True, max_length=200)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('ship_idempotency_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sales.salesorder')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'sal_shipment',
            },
        ),
        migrations.CreateModel(
            name='SalesShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('picked_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('shipped_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorderline')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryreservation')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.salesshipment')),
            ],
            options={
                'db_table': 'sal_shipment_line',
            },
        ),
        migrations.AddIndex(
            model_name='salesshipment',
            index=models.Index(fields=['company', 'status', 'created_at'], name='sal_shipment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesshipment',
            index=models.Index(fields=['carrier_code', 'tracking_no'], name='sal_shipment_tracking_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesshipment',
            constraint=models.UniqueConstraint(fields=('company', 'shipment_no'), name='sal_shipment_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='salesshipmentline',
            constraint=models.UniqueConstraint(fields=('shipment', 'line_no'), name='sal_shipment_line_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='salesshipmentline',
            constraint=models.UniqueConstraint(fields=('shipment', 'reservation'), name='sal_shipment_reservation_uniq'),
        ),
        migrations.AddConstraint(
            model_name='salesshipmentline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('picked_qty__gte', 0), ('shipped_qty__gte', 0)), name='sal_shipment_line_quantities_ck'),
        ),
        migrations.AddConstraint(
            model_name='salesshipmentline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', models.F('picked_qty'))), name='sal_shipment_picked_lte_qty_ck'),
        ),
        migrations.AddConstraint(
            model_name='salesshipmentline',
            constraint=models.CheckConstraint(condition=models.Q(('picked_qty__gte', models.F('shipped_qty'))), name='sal_shipment_shipped_lte_picked_ck'),
        ),
    ]
