# Generated by Django 5.2.17 on 2026-08-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_limitededitionpool_productserial_and_more'),
        ('sales', '0004_salesshipment_salesshipmentline_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesorderline',
            name='sal_order_line_quantities_nonnegative_ck',
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='returned_qty',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__gte', 0), ('shipped_qty__gte', 0), ('returned_qty__gte', 0), ('cancelled_qty__gte', 0)), name='sal_order_line_quantities_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('returned_qty__lte', models.F('shipped_qty'))), name='sal_order_line_returned_lte_shipped_ck'),
        ),
    ]
