# Generated by Django 5.2.17 on 2026-08-22 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0003_limitededitionpool_productserial_and_more'),
        ('sales', '0005_remove_salesorderline_sal_order_line_quantities_nonnegative_ck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresaleCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('campaign_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('promised_delivery_date', models.DateField()),
                ('capacity_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('allocated_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('closed', '关闭'), ('cancelled', '取消')], default='draft', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('sales_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.saleschannel')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
            ],
            options={
                'db_table': 'sal_presale_campaign',
            },
        ),
        migrations.CreateModel(
            name='PresaleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('promised_delivery_date', models.DateField()),
                ('status', models.CharField(default='allocated', max_length=16)),
                ('sales_order_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='presale_allocation', to='sales.salesorderline')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.presalecampaign')),
            ],
            options={
                'db_table': 'sal_presale_allocation',
            },
        ),
        migrations.CreateModel(
            name='SupplyDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('demand_no', models.CharField(max_length=100)),
                ('shortage_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('supplied_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('strategy', models.CharField(choices=[('purchase', '采购'), ('production', '生产'), ('prepack', '预包装'), ('transfer', '调拨'), ('presale', '预售等待')], max_length=16)),
                ('required_date', models.DateField()),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', '待处理'), ('planned', '已计划'), ('partial', '部分供应'), ('fulfilled', '已满足'), ('cancelled', '已取消')], default='open', max_length=16)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_demands', to='sales.salesorderline')),
            ],
            options={
                'db_table': 'sal_supply_demand',
            },
        ),
        migrations.CreateModel(
            name='SupplyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('source_type', models.CharField(max_length=32)),
                ('source_id', models.CharField(max_length=100)),
                ('planned_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('received_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='planned', max_length=16)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.supplydemand')),
            ],
            options={
                'db_table': 'sal_supply_allocation',
            },
        ),
        migrations.AddConstraint(
            model_name='presalecampaign',
            constraint=models.UniqueConstraint(fields=('company', 'campaign_code'), name='sal_presale_campaign_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='presalecampaign',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='sal_presale_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='presalecampaign',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_qty__gt', 0), ('allocated_qty__gte', 0), ('allocated_qty__lte', models.F('capacity_qty'))), name='sal_presale_capacity_ck'),
        ),
        migrations.AddConstraint(
            model_name='presaleallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sal_presale_allocation_qty_ck'),
        ),
        migrations.AddConstraint(
            model_name='supplydemand',
            constraint=models.UniqueConstraint(fields=('company', 'demand_no'), name='sal_supply_demand_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supplydemand',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='sal_supply_demand_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supplydemand',
            constraint=models.CheckConstraint(condition=models.Q(('shortage_qty__gt', 0), ('supplied_qty__gte', 0), ('supplied_qty__lte', models.F('shortage_qty'))), name='sal_supply_demand_qty_ck'),
        ),
        migrations.AddConstraint(
            model_name='supplyallocation',
            constraint=models.UniqueConstraint(fields=('demand', 'source_type', 'source_id'), name='sal_supply_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supplyallocation',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gt', 0), ('received_qty__gte', 0), ('received_qty__lte', models.F('planned_qty'))), name='sal_supply_allocation_qty_ck'),
        ),
    ]
