# Generated by Django 5.2.17 on 2026-08-22 16:46

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_stockcount_stockcountline_stocktransfer_and_more'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0002_material_productattribute_categoryattribute_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('bom_no', models.CharField(max_length=100)),
                ('bom_type', models.CharField(choices=[('production', '生产BOM'), ('packaging', '包装BOM')], max_length=32)),
                ('version', models.CharField(max_length=50)),
                ('output_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已批准'), ('active', '启用'), ('obsolete', '已作废')], default='draft', max_length=32)),
                ('approval_reference', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='products.productsku')),
            ],
            options={
                'db_table': 'mfg_bom',
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('standard_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('expected_loss_rate', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('issue_method', models.CharField(choices=[('manual', '手工领料'), ('backflush', '倒冲')], default='manual', max_length=32)),
                ('is_critical', models.BooleanField(default=False)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='manufacturing.billofmaterial')),
                ('component_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasure')),
            ],
            options={
                'db_table': 'mfg_bom_item',
            },
        ),
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('issue_no', models.CharField(max_length=100)),
                ('issued_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(default='posted', max_length=32)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'mfg_material_issue',
            },
        ),
        migrations.CreateModel(
            name='MaterialIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('planned_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('actual_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('component_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='manufacturing.materialissue')),
                ('source_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybalance')),
            ],
            options={
                'db_table': 'mfg_material_issue_line',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('production_order_no', models.CharField(max_length=100)),
                ('planned_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('completed_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('accepted_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('rejected_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已批准'), ('released', '已下达'), ('waiting_material', '待料'), ('in_progress', '生产中'), ('partially_completed', '部分完工'), ('completed', '已完工'), ('closed', '已结案'), ('cancelled', '已取消')], default='draft', max_length=32)),
                ('version_no', models.PositiveBigIntegerField(default=1)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.billofmaterial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'mfg_production_order',
            },
        ),
        migrations.CreateModel(
            name='ProductionConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('standard_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('issued_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('returned_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('actual_consumed_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('loss_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('loss_rate', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('base_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('component_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='manufacturing.productionorder')),
            ],
            options={
                'db_table': 'mfg_consumption',
            },
        ),
        migrations.CreateModel(
            name='ProductionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('completion_no', models.CharField(max_length=100)),
                ('accepted_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('rejected_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('completed_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('accepted_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_completions', to='inventory.inventorybalance')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rejected_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_completions', to='inventory.inventorybalance')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='manufacturing.productionorder')),
            ],
            options={
                'db_table': 'mfg_production_completion',
            },
        ),
        migrations.AddField(
            model_name='materialissue',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='manufacturing.productionorder'),
        ),
        migrations.AddIndex(
            model_name='billofmaterial',
            index=models.Index(fields=['company', 'product_sku', 'bom_type', 'status', 'valid_from'], name='mfg_bom_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.UniqueConstraint(fields=('company', 'bom_no'), name='mfg_bom_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.UniqueConstraint(fields=('product_sku', 'bom_type', 'version'), name='mfg_bom_product_type_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('output_qty__gt', 0)), name='mfg_bom_output_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='mfg_bom_valid_period_ck'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterialitem',
            constraint=models.UniqueConstraint(fields=('bom', 'line_no'), name='mfg_bom_item_line_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterialitem',
            constraint=models.UniqueConstraint(fields=('bom', 'component_sku'), name='mfg_bom_component_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterialitem',
            constraint=models.CheckConstraint(condition=models.Q(('standard_qty__gt', 0)), name='mfg_bom_item_qty_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterialitem',
            constraint=models.CheckConstraint(condition=models.Q(('expected_loss_rate__gte', 0), ('expected_loss_rate__lte', 1)), name='mfg_bom_item_loss_rate_ck'),
        ),
        migrations.AddConstraint(
            model_name='materialissueline',
            constraint=models.UniqueConstraint(fields=('issue', 'line_no'), name='mfg_issue_line_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialissueline',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gte', 0), ('actual_qty__gt', 0)), name='mfg_issue_line_quantities_ck'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['company', 'status', 'planned_start'], name='mfg_order_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('company', 'production_order_no'), name='mfg_order_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gt', 0), ('completed_qty__gte', 0), ('accepted_qty__gte', 0), ('rejected_qty__gte', 0)), name='mfg_order_quantities_ck'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gte', models.F('completed_qty'))), name='mfg_order_completed_lte_planned_ck'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('completed_qty', django.db.models.expressions.CombinedExpression(models.F('accepted_qty'), '+', models.F('rejected_qty')))), name='mfg_order_result_sum_ck'),
        ),
        migrations.AddConstraint(
            model_name='productionconsumption',
            constraint=models.UniqueConstraint(fields=('production_order', 'component_sku'), name='mfg_consumption_component_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productionconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('standard_qty__gte', 0), ('issued_qty__gte', 0), ('returned_qty__gte', 0), ('actual_consumed_qty__gte', 0), ('loss_qty__gte', 0)), name='mfg_consumption_quantities_ck'),
        ),
        migrations.AddConstraint(
            model_name='productionconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('issued_qty__gte', django.db.models.expressions.CombinedExpression(models.F('returned_qty'), '+', models.F('actual_consumed_qty')))), name='mfg_consumption_usage_lte_issued_ck'),
        ),
        migrations.AddConstraint(
            model_name='productioncompletion',
            constraint=models.UniqueConstraint(fields=('production_order', 'completion_no'), name='mfg_completion_order_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productioncompletion',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_qty__gte', 0), ('rejected_qty__gte', 0), models.Q(('accepted_qty__gt', 0), ('rejected_qty__gt', 0), _connector='OR')), name='mfg_completion_quantities_ck'),
        ),
        migrations.AddConstraint(
            model_name='materialissue',
            constraint=models.UniqueConstraint(fields=('production_order', 'issue_no'), name='mfg_issue_order_no_uniq'),
        ),
    ]
