# Generated by Django 5.2.17 on 2026-08-22 17:38

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockcount_stockcountline_stocktransfer_and_more'),
        ('manufacturing', '0001_initial'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0003_limitededitionpool_productserial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('routing_no', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('obsolete', '作废')], default='draft', max_length=16)),
                ('approval_reference', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
            ],
            options={
                'db_table': 'mfg_routing',
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.routing'),
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('sequence', models.PositiveIntegerField()),
                ('operation_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('setup_minutes', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('run_minutes_per_unit', models.DecimalField(decimal_places=6, max_digits=20)),
                ('queue_minutes', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('inspection_required', models.BooleanField(default=False)),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='manufacturing.routing')),
            ],
            options={
                'db_table': 'mfg_routing_operation',
            },
        ),
        migrations.CreateModel(
            name='OperationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('report_no', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('good_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('rejected_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('labor_minutes', models.DecimalField(decimal_places=6, max_digits=20)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_reports', to='manufacturing.productionorder')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.routingoperation')),
            ],
            options={
                'db_table': 'mfg_operation_report',
            },
        ),
        migrations.CreateModel(
            name='SubcontractOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('subcontract_no', models.CharField(max_length=100)),
                ('ordered_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('received_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('accepted_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('rejected_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('processing_unit_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('expected_return_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已批准'), ('material_sent', '已发料'), ('processing', '加工中'), ('received', '已收回'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('version_no', models.PositiveBigIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_subcontracts', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productionorder')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_requests', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'mfg_subcontract_order',
            },
        ),
        migrations.CreateModel(
            name='SubcontractMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('planned_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('sent_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('consumed_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('returned_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('component_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('source_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybalance')),
                ('subcontract_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='manufacturing.subcontractorder')),
            ],
            options={
                'db_table': 'mfg_subcontract_material',
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('work_center_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('capacity_per_hour', models.DecimalField(decimal_places=6, max_digits=20)),
                ('hourly_rate', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
            ],
            options={
                'db_table': 'mfg_work_center',
            },
        ),
        migrations.AddField(
            model_name='routingoperation',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.workcenter'),
        ),
        migrations.CreateModel(
            name='ProductionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('suggestion_no', models.CharField(max_length=100)),
                ('suggested_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('required_date', models.DateField()),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=100)),
                ('reason_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(default='open', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('production_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_suggestion', to='manufacturing.productionorder')),
            ],
            options={
                'db_table': 'mfg_production_suggestion',
                'constraints': [models.UniqueConstraint(fields=('company', 'suggestion_no'), name='mfg_suggestion_no_uniq'), models.CheckConstraint(condition=models.Q(('suggested_qty__gt', 0)), name='mfg_suggestion_qty_ck')],
            },
        ),
        migrations.AddConstraint(
            model_name='routing',
            constraint=models.UniqueConstraint(fields=('company', 'routing_no'), name='mfg_routing_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='routing',
            constraint=models.UniqueConstraint(fields=('product_sku', 'version'), name='mfg_routing_product_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='routing',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='mfg_routing_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='operationreport',
            constraint=models.UniqueConstraint(fields=('production_order', 'report_no'), name='mfg_operation_report_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='operationreport',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__gt', models.F('started_at'))), name='mfg_operation_report_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='operationreport',
            constraint=models.CheckConstraint(condition=models.Q(('good_qty__gte', 0), ('rejected_qty__gte', 0), ('labor_minutes__gte', 0)), name='mfg_operation_report_values_ck'),
        ),
        migrations.AddConstraint(
            model_name='subcontractorder',
            constraint=models.UniqueConstraint(fields=('company', 'subcontract_no'), name='mfg_subcontract_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subcontractorder',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gt', 0), ('received_qty__gte', 0), ('accepted_qty__gte', 0), ('rejected_qty__gte', 0), ('processing_unit_price__gte', 0)), name='mfg_subcontract_values_ck'),
        ),
        migrations.AddConstraint(
            model_name='subcontractorder',
            constraint=models.CheckConstraint(condition=models.Q(('received_qty', django.db.models.expressions.CombinedExpression(models.F('accepted_qty'), '+', models.F('rejected_qty'))), ('received_qty__lte', models.F('ordered_qty'))), name='mfg_subcontract_result_ck'),
        ),
        migrations.AddConstraint(
            model_name='subcontractmaterial',
            constraint=models.UniqueConstraint(fields=('subcontract_order', 'component_sku'), name='mfg_subcontract_material_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subcontractmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gt', 0), ('sent_qty__gte', 0), ('consumed_qty__gte', 0), ('returned_qty__gte', 0), ('sent_qty__lte', models.F('planned_qty')), ('sent_qty__gte', django.db.models.expressions.CombinedExpression(models.F('consumed_qty'), '+', models.F('returned_qty')))), name='mfg_subcontract_material_qty_ck'),
        ),
        migrations.AddConstraint(
            model_name='workcenter',
            constraint=models.UniqueConstraint(fields=('company', 'work_center_code'), name='mfg_work_center_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workcenter',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_per_hour__gt', 0), ('hourly_rate__gte', 0)), name='mfg_work_center_values_ck'),
        ),
        migrations.AddConstraint(
            model_name='routingoperation',
            constraint=models.UniqueConstraint(fields=('routing', 'sequence'), name='mfg_routing_operation_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='routingoperation',
            constraint=models.CheckConstraint(condition=models.Q(('setup_minutes__gte', 0), ('run_minutes_per_unit__gt', 0), ('queue_minutes__gte', 0)), name='mfg_routing_operation_time_ck'),
        ),
    ]
