# Generated by Django 5.2.17 on 2026-08-22 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('report_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(max_length=50)),
                ('allowed_filters', models.JSONField(default=list)),
                ('default_columns', models.JSONField(default=list)),
                ('permission_code', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'ana_report_definition',
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel')], max_length=8)),
                ('filters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '完成'), ('failed', '失败'), ('expired', '已过期')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('file_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.fileobject')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.reportdefinition')),
            ],
            options={
                'db_table': 'ana_export_job',
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('snapshot_no', models.CharField(max_length=100)),
                ('as_of', models.DateTimeField()),
                ('filters', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('result_sha256', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.reportdefinition')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ana_report_snapshot',
            },
        ),
        migrations.AddConstraint(
            model_name='reportdefinition',
            constraint=models.UniqueConstraint(fields=('company', 'report_code'), name='ana_report_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshot',
            constraint=models.UniqueConstraint(fields=('company', 'snapshot_no'), name='ana_report_snapshot_no_uniq'),
        ),
    ]
