# Generated by Django 5.2.17 on 2026-08-22 16:26

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0002_material_productattribute_categoryattribute_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('purchase_order_no', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('tax_total', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_total', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已审批'), ('issued', '已下达'), ('partially_received', '部分收货'), ('received', '全部收货'), ('closed', '已关闭'), ('cancelled', '已取消')], default='draft', max_length=32)),
                ('approval_status', models.CharField(default='pending', max_length=32)),
                ('version_no', models.PositiveBigIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'pur_purchase_order',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('receipt_no', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('received', '已收货'), ('inspection', '待验收'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=32)),
                ('supplier_delivery_no', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorder')),
            ],
            options={
                'db_table': 'pur_goods_receipt',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('ordered_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('received_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('accepted_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('rejected_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('returned_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tax_rate', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=6, max_digits=20)),
                ('base_line_total', models.DecimalField(decimal_places=6, max_digits=20)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=32)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchasing.purchaseorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
            ],
            options={
                'db_table': 'pur_purchase_order_line',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('received_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('pending_inspection_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('lot_no', models.CharField(blank=True, max_length=100)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchasing.goodsreceipt')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('staging_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouselocation')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.purchaseorderline')),
            ],
            options={
                'db_table': 'pur_goods_receipt_line',
            },
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('inspection_no', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(default='pending', max_length=32)),
                ('status', models.CharField(choices=[('pending', '待检'), ('in_progress', '检验中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inspection', to='purchasing.goodsreceipt')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'pur_quality_inspection',
            },
        ),
        migrations.CreateModel(
            name='QualityInspectionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('inspected_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('accepted_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('rejected_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('pending_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('disposition', models.CharField(blank=True, max_length=32)),
                ('defect_code', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchasing.qualityinspection')),
                ('receipt_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='purchasing.goodsreceiptline')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
            ],
            options={
                'db_table': 'pur_quality_inspection_line',
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'supplier', 'status'], name='pur_po_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('company', 'purchase_order_no'), name='pur_po_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='pur_po_exchange_rate_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('tax_total__gte', 0), ('total__gte', 0), ('base_total__gte', 0)), name='pur_po_amounts_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(fields=('company', 'receipt_no'), name='pur_receipt_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'line_no'), name='pur_po_line_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gt', 0), ('received_qty__gte', 0), ('accepted_qty__gte', 0), ('rejected_qty__gte', 0), ('returned_qty__gte', 0)), name='pur_po_line_quantities_ck'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gte', models.F('received_qty'))), name='pur_po_line_received_lte_ordered_ck'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('received_qty__gte', django.db.models.expressions.CombinedExpression(models.F('accepted_qty'), '+', models.F('rejected_qty')))), name='pur_po_line_inspected_lte_received_ck'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('returned_qty__lte', models.F('rejected_qty'))), name='pur_po_line_returned_lte_rejected_ck'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'purchase_order_line'), name='pur_receipt_po_line_uniq'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('received_qty__gt', 0), ('pending_inspection_qty__gte', 0), ('received_qty__gte', models.F('pending_inspection_qty'))), name='pur_receipt_line_quantities_ck'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspection',
            constraint=models.UniqueConstraint(fields=('company', 'inspection_no'), name='pur_inspection_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspectionline',
            constraint=models.CheckConstraint(condition=models.Q(('inspected_qty__gt', 0), ('accepted_qty__gte', 0), ('rejected_qty__gte', 0), ('pending_qty__gte', 0)), name='pur_inspection_line_quantities_ck'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspectionline',
            constraint=models.CheckConstraint(condition=models.Q(('inspected_qty', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('accepted_qty'), '+', models.F('rejected_qty')), '+', models.F('pending_qty')))), name='pur_inspection_line_sum_ck'),
        ),
    ]
