# Generated by Django 5.2.17 on 2026-08-22 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockcount_stockcountline_stocktransfer_and_more'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0003_limitededitionpool_productserial_and_more'),
        ('purchasing', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('requisition_no', models.CharField(max_length=100)),
                ('required_date', models.DateField()),
                ('source_type', models.CharField(default='manual', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准'), ('sourcing', '询价中'), ('ordered', '已下单'), ('closed', '已关闭'), ('rejected', '已拒绝')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('version_no', models.PositiveBigIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_requisitions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'pur_requisition',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('requested_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('ordered_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('reason', models.TextField(blank=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchasing.purchaserequisition')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('suggested_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'pur_requisition_line',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('return_no', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已批准'), ('dispatched', '已退运'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('version_no', models.PositiveBigIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.purchaseorder')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'pur_return',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('return_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('dispatched_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('inventory_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybalance')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.purchaseorderline')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchasing.purchasereturn')),
            ],
            options={
                'db_table': 'pur_return_line',
            },
        ),
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('rfq_no', models.CharField(max_length=100)),
                ('quote_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('issued', '已发出'), ('evaluating', '评估中'), ('awarded', '已定标'), ('closed', '已关闭')], default='draft', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='purchasing.purchaserequisition')),
            ],
            options={
                'db_table': 'pur_rfq',
            },
        ),
        migrations.CreateModel(
            name='RfqSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('invited_at', models.DateTimeField()),
                ('response_status', models.CharField(default='pending', max_length=16)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='purchasing.requestforquotation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'pur_rfq_supplier',
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('on_time_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('acceptance_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('price_variance_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('score', models.DecimalField(decimal_places=6, max_digits=12)),
                ('metric_snapshot', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'pur_supplier_performance',
            },
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('quote_no', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('freight_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('delivery_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(default='submitted', max_length=16)),
                ('score_snapshot', models.JSONField(default=dict)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='purchasing.requestforquotation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
            ],
            options={
                'db_table': 'pur_supplier_quote',
            },
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='awarded_quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='awarded_rfq', to='purchasing.supplierquote'),
        ),
        migrations.CreateModel(
            name='SupplierQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tax_rate', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchasing.supplierquote')),
                ('requisition_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.purchaserequisitionline')),
            ],
            options={
                'db_table': 'pur_supplier_quote_line',
            },
        ),
        migrations.AddConstraint(
            model_name='purchaserequisition',
            constraint=models.UniqueConstraint(fields=('company', 'requisition_no'), name='pur_requisition_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequisitionline',
            constraint=models.UniqueConstraint(fields=('requisition', 'line_no'), name='pur_requisition_line_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequisitionline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_qty__gt', 0), ('ordered_qty__gte', 0), ('ordered_qty__lte', models.F('requested_qty'))), name='pur_requisition_line_qty_ck'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.UniqueConstraint(fields=('company', 'return_no'), name='pur_return_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='pur_return_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnline',
            constraint=models.UniqueConstraint(fields=('purchase_return', 'purchase_order_line'), name='pur_return_order_line_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnline',
            constraint=models.CheckConstraint(condition=models.Q(('return_qty__gt', 0), ('dispatched_qty__gte', 0), ('dispatched_qty__lte', models.F('return_qty'))), name='pur_return_line_qty_ck'),
        ),
        migrations.AddConstraint(
            model_name='rfqsupplier',
            constraint=models.UniqueConstraint(fields=('rfq', 'supplier'), name='pur_rfq_supplier_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supplierperformancesnapshot',
            constraint=models.UniqueConstraint(fields=('company', 'supplier', 'period_start', 'period_end'), name='pur_supplier_perf_period_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supplierperformancesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='pur_supplier_perf_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='supplierquote',
            constraint=models.UniqueConstraint(fields=('rfq', 'supplier', 'quote_no'), name='pur_quote_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supplierquote',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0), ('freight_amount__gte', 0), ('tax_amount__gte', 0), ('total_amount__gte', 0)), name='pur_quote_amount_ck'),
        ),
        migrations.AddConstraint(
            model_name='requestforquotation',
            constraint=models.UniqueConstraint(fields=('company', 'rfq_no'), name='pur_rfq_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supplierquoteline',
            constraint=models.UniqueConstraint(fields=('quote', 'requisition_line'), name='pur_quote_req_line_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supplierquoteline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_price__gte', 0), ('tax_rate__gte', 0)), name='pur_quote_line_values_ck'),
        ),
    ]
