# Generated by Django 5.2.17 on 2026-08-22 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('aggregate_version', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(max_length=150)),
                ('event_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', '待投递'), ('processing', '处理中'), ('published', '已投递'), ('failed', '失败'), ('dead', '死信')], default='pending', max_length=16)),
                ('priority', models.SmallIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=100)),
                ('trace_id', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'evt_outbox',
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['status', 'next_attempt_at', 'priority', 'id'], name='evt_outbox_pending_claim_idx'), models.Index(fields=['company', 'occurred_at'], name='evt_outbox_company_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('aggregate_type', 'aggregate_id', 'event_type', 'aggregate_version'), name='evt_outbox_aggregate_event_version_uniq')],
            },
        ),
    ]
