# Generated by Django 5.2.17 on 2026-08-22 14:11

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0002_material_productattribute_categoryattribute_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('lot_no', models.CharField(max_length=100)),
                ('supplier_lot_no', models.CharField(blank=True, max_length=100)),
                ('manufactured_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('is_no_lot_sentinel', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='products.productsku')),
            ],
            options={
                'db_table': 'inv_lot',
            },
        ),
        migrations.CreateModel(
            name='InventoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('status_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_physical', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'inv_status',
            },
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('quantity_delta', models.DecimalField(decimal_places=6, max_digits=20)),
                ('before_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('after_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('reference_type', models.CharField(max_length=80)),
                ('reference_id', models.PositiveBigIntegerField()),
                ('reference_no', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouselocation')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorylot')),
                ('inventory_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorystatus')),
            ],
            options={
                'db_table': 'inv_ledger',
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('reserved_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('locked_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouselocation')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorylot')),
                ('inventory_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorystatus')),
            ],
            options={
                'db_table': 'inv_balance',
            },
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.UniqueConstraint(fields=('company', 'sku', 'lot_no'), name='inv_lot_company_sku_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('expires_on__isnull', True), ('manufactured_on__isnull', True), ('expires_on__gt', models.F('manufactured_on')), _connector='OR'), name='inv_lot_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='inventorystatus',
            constraint=models.UniqueConstraint(fields=('company', 'status_code'), name='inv_status_company_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['company', 'sku', 'occurred_at', 'id'], name='inv_ledger_sku_time_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inv_ledger_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['company', 'warehouse', 'sku', 'inventory_status'], name='inv_balance_stock_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('company', 'sku', 'warehouse', 'location', 'inventory_status', 'lot'), name='inv_balance_dimension_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_qty__gte', 0)), name='inv_balance_on_hand_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__gte', 0)), name='inv_balance_reserved_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('locked_qty__gte', 0)), name='inv_balance_locked_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_qty__gte', django.db.models.expressions.CombinedExpression(models.F('reserved_qty'), '+', models.F('locked_qty')))), name='inv_balance_committed_lte_on_hand_ck'),
        ),
    ]
