# Generated by Django 5.2.17 on 2026-08-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('reservation_no', models.CharField(max_length=100)),
                ('reserved_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('consumed_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('released_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('active', '有效'), ('consumed', '已消耗'), ('released', '已释放'), ('expired', '已过期')], default='active', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybalance')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'inv_reservation',
            },
        ),
    ]
