# Generated by Django 5.2.17 on 2026-08-22 14:14

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryreservation'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreservation',
            name='sales_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='sales.salesorderline'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['sales_order_line', 'status'], name='inv_reservation_order_line_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['balance', 'status'], name='inv_reservation_balance_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.UniqueConstraint(fields=('company', 'reservation_no'), name='inv_reservation_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__gt', 0)), name='inv_reservation_reserved_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_qty__gte', 0), ('released_qty__gte', 0)), name='inv_reservation_used_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__gte', django.db.models.expressions.CombinedExpression(models.F('consumed_qty'), '+', models.F('released_qty')))), name='inv_reservation_used_lte_reserved_ck'),
        ),
    ]
