# Generated by Django 5.2.17 on 2026-08-22 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryreservation_sales_order_line_and_more'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0002_material_productattribute_categoryattribute_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('count_no', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('counting', '盘点中'), ('pending_approval', '待审批'), ('posted', '已过账'), ('cancelled', '已取消')], default='draft', max_length=32)),
                ('version_no', models.PositiveBigIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('post_idempotency_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'inv_stock_count',
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('book_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('difference_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybalance')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.stockcount')),
            ],
            options={
                'db_table': 'inv_stock_count_line',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('transfer_no', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已批准'), ('in_transit', '在途'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=32)),
                ('version_no', models.PositiveBigIntegerField(default=1)),
                ('dispatch_idempotency_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('receipt_idempotency_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfers', to='warehouse.warehouse')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_transfers', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'inv_stock_transfer',
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('requested_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('dispatched_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('received_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('difference_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('destination_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_destination_lines', to='inventory.inventorybalance')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('source_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_source_lines', to='inventory.inventorybalance')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.stocktransfer')),
            ],
            options={
                'db_table': 'inv_stock_transfer_line',
            },
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['company', 'warehouse', 'status'], name='inv_count_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.UniqueConstraint(fields=('company', 'count_no'), name='inv_count_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.UniqueConstraint(fields=('count', 'line_no'), name='inv_count_line_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.UniqueConstraint(fields=('count', 'balance'), name='inv_count_balance_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('book_qty__gte', 0), models.Q(('counted_qty__isnull', True), ('counted_qty__gte', 0), _connector='OR')), name='inv_count_line_quantities_ck'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['company', 'status', 'created_at'], name='inv_transfer_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(fields=('company', 'transfer_no'), name='inv_transfer_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_warehouse', models.F('destination_warehouse')), _negated=True), name='inv_transfer_warehouses_different_ck'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.UniqueConstraint(fields=('transfer', 'line_no'), name='inv_transfer_line_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_qty__gt', 0), ('dispatched_qty__gte', 0), ('received_qty__gte', 0)), name='inv_transfer_line_quantities_ck'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_qty__gte', models.F('dispatched_qty'))), name='inv_transfer_dispatched_lte_requested_ck'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('dispatched_qty__gte', models.F('received_qty'))), name='inv_transfer_received_lte_dispatched_ck'),
        ),
    ]
