# Generated by Django 5.2.17 on 2026-08-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0002_material_productattribute_categoryattribute_and_more'),
        ('sales', '0002_salesorderconfirmation_salesorderline_line_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('level_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('default_discount_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'prc_agent_level',
            },
        ),
        migrations.CreateModel(
            name='AgentDiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('discount_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productcategory')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('agent_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.agentlevel')),
            ],
            options={
                'db_table': 'prc_agent_discount_rule',
            },
        ),
        migrations.CreateModel(
            name='CustomerSpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('special_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('special_discount_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('can_break_floor', models.BooleanField(default=False)),
                ('approval_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.party')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
            ],
            options={
                'db_table': 'prc_customer_special_price',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('price_list_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('customer_type', models.CharField(blank=True, max_length=32)),
                ('tax_mode', models.CharField(choices=[('tax_included', '含税'), ('tax_excluded', '未税')], max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('expired', '已过期'), ('disabled', '停用')], default='draft', max_length=32)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.saleschannel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.currency')),
            ],
            options={
                'db_table': 'prc_price_list',
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('minimum_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('minimum_discount_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('min_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('max_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pricing.pricelist')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasure')),
            ],
            options={
                'db_table': 'prc_price_list_item',
            },
        ),
        migrations.CreateModel(
            name='PricingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('policy_code', models.CharField(max_length=50)),
                ('customer_special_priority', models.IntegerField(default=500)),
                ('agent_sku_priority', models.IntegerField(default=400)),
                ('agent_category_priority', models.IntegerField(default=300)),
                ('channel_priority', models.IntegerField(default=200)),
                ('standard_priority', models.IntegerField(default=100)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
            ],
            options={
                'db_table': 'prc_policy',
            },
        ),
        migrations.AddConstraint(
            model_name='agentlevel',
            constraint=models.UniqueConstraint(fields=('company', 'level_code'), name='prc_agent_level_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='agentdiscountrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sku__isnull', False), ('product_category__isnull', True)), models.Q(('sku__isnull', True), ('product_category__isnull', False)), _connector='OR'), name='prc_agent_rule_one_scope_ck'),
        ),
        migrations.AddConstraint(
            model_name='agentdiscountrule',
            constraint=models.CheckConstraint(condition=models.Q(('discount_rate__gt', 0), ('discount_rate__lte', 1)), name='prc_agent_rule_discount_ck'),
        ),
        migrations.AddConstraint(
            model_name='agentdiscountrule',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='prc_agent_rule_period_ck'),
        ),
        migrations.AddConstraint(
            model_name='customerspecialprice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('special_price__isnull', False), ('special_discount_rate__isnull', True)), models.Q(('special_price__isnull', True), ('special_discount_rate__isnull', False)), _connector='OR'), name='prc_special_price_one_method_ck'),
        ),
        migrations.AddConstraint(
            model_name='customerspecialprice',
            constraint=models.CheckConstraint(condition=models.Q(('special_discount_rate__isnull', True), models.Q(('special_discount_rate__gt', 0), ('special_discount_rate__lte', 1)), _connector='OR'), name='prc_special_discount_ck'),
        ),
        migrations.AddConstraint(
            model_name='customerspecialprice',
            constraint=models.CheckConstraint(condition=models.Q(('can_break_floor', False), ('approval_id__isnull', False), _connector='OR'), name='prc_special_floor_approval_ck'),
        ),
        migrations.AddConstraint(
            model_name='customerspecialprice',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='prc_special_period_ck'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('company', 'price_list_no'), name='prc_price_list_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='prc_price_list_period_ck'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.UniqueConstraint(fields=('price_list', 'sku', 'uom', 'min_qty'), name='prc_price_item_scope_qty_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='prc_item_price_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_price__isnull', True), ('minimum_price__gte', 0), _connector='OR'), name='prc_item_floor_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.CheckConstraint(condition=models.Q(('max_qty__isnull', True), ('max_qty__gt', models.F('min_qty')), _connector='OR'), name='prc_item_qty_range_ck'),
        ),
        migrations.AddConstraint(
            model_name='pricingpolicy',
            constraint=models.UniqueConstraint(fields=('company', 'policy_code', 'valid_from'), name='prc_policy_company_code_start_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pricingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='prc_policy_period_ck'),
        ),
    ]
