# Generated by Django 5.2.17 on 2026-08-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_agentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('approved', '已批准'), ('active', '启用'), ('expired', '已过期'), ('disabled', '停用')], default='draft', max_length=32),
        ),
    ]
