# Generated by Django 5.2.17 on 2026-08-22 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_stockcount_stockcountline_stocktransfer_and_more'),
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
        ('products', '0002_material_productattribute_categoryattribute_and_more'),
        ('sales', '0004_salesshipment_salesshipmentline_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('plan_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('trade_type', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('obsolete', '已作废')], default='draft', max_length=32)),
                ('approval_reference', models.CharField(blank=True, max_length=200)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.saleschannel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_plans', to='products.productsku')),
            ],
            options={
                'db_table': 'ppk_packaging_plan',
            },
        ),
        migrations.CreateModel(
            name='PackagingPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('standard_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('allowed_loss_rate', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('returnable_on_breakdown', models.BooleanField(default=False)),
                ('material_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='prepack.packagingplan')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasure')),
            ],
            options={
                'db_table': 'ppk_packaging_plan_item',
            },
        ),
        migrations.CreateModel(
            name='PrepackBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('breakdown_no', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('approval_reference', models.CharField(max_length=200)),
                ('occurred_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prepacked_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepack_breakdown_sources', to='inventory.inventorybalance')),
                ('restored_product_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepack_breakdown_products', to='inventory.inventorybalance')),
            ],
            options={
                'db_table': 'ppk_breakdown',
            },
        ),
        migrations.CreateModel(
            name='PrepackBreakdownMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('returned_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('breakdown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned_materials', to='prepack.prepackbreakdown')),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prepack.packagingplanitem')),
                ('return_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybalance')),
            ],
            options={
                'db_table': 'ppk_breakdown_material',
            },
        ),
        migrations.CreateModel(
            name='PrepackExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('execution_no', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('executed_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepack_source_executions', to='inventory.inventorybalance')),
                ('target_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepack_target_executions', to='inventory.inventorybalance')),
            ],
            options={
                'db_table': 'ppk_execution',
            },
        ),
        migrations.CreateModel(
            name='PrepackMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('standard_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('actual_used_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('loss_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_usages', to='prepack.prepackexecution')),
                ('material_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybalance')),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prepack.packagingplanitem')),
            ],
            options={
                'db_table': 'ppk_material_usage',
            },
        ),
        migrations.CreateModel(
            name='PrepackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('prepack_order_no', models.CharField(max_length=100)),
                ('planned_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('completed_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('broken_down_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已批准'), ('packaging', '包装中'), ('partially_completed', '部分完成'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=32)),
                ('version_no', models.PositiveBigIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('packaging_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prepack.packagingplan')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsku')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepack_source_orders', to='warehouse.warehouselocation')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepack_target_orders', to='warehouse.warehouselocation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'ppk_order',
            },
        ),
        migrations.AddField(
            model_name='prepackexecution',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='prepack.prepackorder'),
        ),
        migrations.AddField(
            model_name='prepackbreakdown',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakdowns', to='prepack.prepackorder'),
        ),
        migrations.AddConstraint(
            model_name='packagingplan',
            constraint=models.UniqueConstraint(fields=('company', 'plan_no'), name='ppk_plan_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='packagingplan',
            constraint=models.UniqueConstraint(fields=('product_sku', 'channel', 'trade_type', 'version'), name='ppk_plan_scope_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='packagingplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'line_no'), name='ppk_plan_item_line_uniq'),
        ),
        migrations.AddConstraint(
            model_name='packagingplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'material_sku'), name='ppk_plan_material_uniq'),
        ),
        migrations.AddConstraint(
            model_name='packagingplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('standard_qty__gt', 0)), name='ppk_plan_item_qty_ck'),
        ),
        migrations.AddConstraint(
            model_name='packagingplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('allowed_loss_rate__gte', 0), ('allowed_loss_rate__lte', 1)), name='ppk_plan_item_loss_ck'),
        ),
        migrations.AddConstraint(
            model_name='prepackbreakdownmaterial',
            constraint=models.UniqueConstraint(fields=('breakdown', 'plan_item'), name='ppk_breakdown_plan_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='prepackbreakdownmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('returned_qty__gt', 0)), name='ppk_breakdown_return_qty_ck'),
        ),
        migrations.AddConstraint(
            model_name='prepackmaterialusage',
            constraint=models.UniqueConstraint(fields=('execution', 'plan_item'), name='ppk_usage_plan_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='prepackmaterialusage',
            constraint=models.CheckConstraint(condition=models.Q(('standard_qty__gte', 0), ('actual_used_qty__gt', 0), ('loss_qty__gte', 0)), name='ppk_usage_quantities_ck'),
        ),
        migrations.AddConstraint(
            model_name='prepackorder',
            constraint=models.UniqueConstraint(fields=('company', 'prepack_order_no'), name='ppk_order_company_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='prepackorder',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gt', 0), ('completed_qty__gte', 0), ('broken_down_qty__gte', 0)), name='ppk_order_quantities_ck'),
        ),
        migrations.AddConstraint(
            model_name='prepackorder',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gte', models.F('completed_qty'))), name='ppk_order_completed_lte_planned_ck'),
        ),
        migrations.AddConstraint(
            model_name='prepackorder',
            constraint=models.CheckConstraint(condition=models.Q(('completed_qty__gte', models.F('broken_down_qty'))), name='ppk_order_breakdown_lte_completed_ck'),
        ),
        migrations.AddConstraint(
            model_name='prepackexecution',
            constraint=models.UniqueConstraint(fields=('order', 'execution_no'), name='ppk_execution_order_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='prepackexecution',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ppk_execution_qty_ck'),
        ),
        migrations.AddConstraint(
            model_name='prepackbreakdown',
            constraint=models.UniqueConstraint(fields=('order', 'breakdown_no'), name='ppk_breakdown_order_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='prepackbreakdown',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ppk_breakdown_qty_ck'),
        ),
    ]
