# Generated by Django 5.2.17 on 2026-08-22 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0003_party_customerprofile_supplierprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('connector_type', models.CharField(max_length=32)),
                ('capabilities', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'int_connector',
            },
        ),
        migrations.CreateModel(
            name='IntegrationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('account_code', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('credential_reference', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('revoked', '已撤销'), ('error', '异常')], default='active', max_length=16)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.company')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.connector')),
            ],
            options={
                'db_table': 'int_account',
            },
        ),
        migrations.CreateModel(
            name='ExternalObjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('object_type', models.CharField(max_length=50)),
                ('internal_id', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=300)),
                ('external_code', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(default='active', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'int_external_mapping',
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('direction', models.CharField(choices=[('in', '入站'), ('out', '出站')], max_length=8)),
                ('event_type', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=300)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('payload_reference', models.CharField(max_length=1000)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('signature_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('succeeded', '成功'), ('failed', '失败'), ('dead', '死信'), ('ignored', '忽略')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=8)),
                ('next_attempt_at', models.DateTimeField()),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('internal_object_type', models.CharField(blank=True, max_length=50)),
                ('internal_object_id', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'int_event',
            },
        ),
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('object_type', models.CharField(max_length=50)),
                ('cursor', models.CharField(blank=True, max_length=1000)),
                ('watermark', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'int_sync_cursor',
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('event_type', models.CharField(max_length=100)),
                ('callback_url', models.URLField(max_length=1000)),
                ('secret_reference', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'int_webhook_endpoint',
            },
        ),
        migrations.AddConstraint(
            model_name='integrationaccount',
            constraint=models.UniqueConstraint(fields=('company', 'connector', 'account_code'), name='int_account_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='externalobjectmapping',
            constraint=models.UniqueConstraint(fields=('account', 'object_type', 'external_id'), name='int_mapping_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='externalobjectmapping',
            constraint=models.UniqueConstraint(fields=('account', 'object_type', 'internal_id'), name='int_mapping_internal_uniq'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['status', 'next_attempt_at'], name='int_event_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationevent',
            constraint=models.UniqueConstraint(fields=('account', 'direction', 'idempotency_key'), name='int_event_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='integrationevent',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gt', 0)), name='int_event_max_attempts_ck'),
        ),
        migrations.AddConstraint(
            model_name='synccursor',
            constraint=models.UniqueConstraint(fields=('account', 'object_type'), name='int_sync_cursor_uniq'),
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.UniqueConstraint(fields=('account', 'event_type', 'callback_url'), name='int_webhook_uniq'),
        ),
    ]
